load(":defs.bzl", "my_rule")

constraint_setting(name = "cpu")

constraint_value(
    name = "x86_64",
    constraint_setting = ":cpu",
)

platform(
    name = "re_platform",
    constraint_values = [":x86_64"],
    exec_properties = {
        "cpu_count": "1",
        "//command_line_option:cpu": "k8",
    },
)

my_rule(
    name = "foo",
)
