load("@rules_rust//rust:defs.bzl", "rust_library")
load("@slug_crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "gazebo",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    crate_features = ["str_pattern_extensions"],
    edition = crate_edition(),
    deps = all_crate_deps(normal = True) + [
        "//gazebo/dupe",
    ],
    proc_macro_deps = all_crate_deps(proc_macro = True) + [
        "//gazebo/gazebo_derive",
    ],
)
