load("@rules_rust//rust:defs.bzl", "rust_library")
load("@slug_crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "dice",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    edition = crate_edition(),
    deps = all_crate_deps(normal = True) + [
        "//allocative/allocative",
        "//dice/dice_error",
        "//dice/dice_futures",
        "//gazebo/cmp_any",
        "//gazebo/dupe",
        "//gazebo/gazebo",
        "//shed/lock_free_hashtable",
        "//shed/lock_free_vec",
    ],
    proc_macro_deps = all_crate_deps(proc_macro = True),
)
