/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

use std::fmt;
use std::str::FromStr;
use std::sync::Arc;

use allocative::Allocative;
use derive_more::Display;
use dupe::Dupe;
use kuro_error::kuro_error;

use crate::cells::name::CellName;

#[derive(Debug, Clone, Dupe, Allocative, PartialEq, Eq)]
pub enum ExternalCellOrigin {
    Bundled(CellName),
    Git(GitCellSetup),
    /// Local path module from bzlmod `local_path_override()`.
    LocalPath(LocalPathCellSetup),
    /// Remote module from bzlmod `bazel_dep()` fetched from a registry (e.g., BCR).
    Bzlmod(BzlmodCellSetup),
    /// Repository created by a repository rule (http_archive, git_repository, etc.)
    RepositoryRule(RepositoryRuleCellSetup),
    /// Repository generated by a module extension (pending lazy execution).
    ExtensionRepo(ExtensionRepoCellSetup),
}

/// Setup for a local path external cell (from bzlmod local_path_override).
#[derive(
    Debug,
    derive_more::Display,
    Clone,
    Dupe,
    Allocative,
    PartialEq,
    Eq,
    Hash
)]
#[display("local_path({}, {})", module_name, path)]
pub struct LocalPathCellSetup {
    /// The bzlmod module name this local path provides.
    pub module_name: Arc<str>,
    /// The local filesystem path (relative to workspace root).
    pub path: Arc<str>,
}

/// Setup for a remote bzlmod module fetched from a registry (e.g., BCR).
#[derive(
    Debug,
    derive_more::Display,
    Clone,
    Dupe,
    Allocative,
    PartialEq,
    Eq,
    Hash
)]
#[display("bzlmod({}, {}, {})", module_name, version, registry_url)]
pub struct BzlmodCellSetup {
    /// The bzlmod module name.
    pub module_name: Arc<str>,
    /// The module version.
    pub version: Arc<str>,
    /// The registry URL this was fetched from (e.g., "https://bcr.bazel.build").
    pub registry_url: Arc<str>,
    /// The absolute path to the cached/extracted source.
    pub source_path: Arc<str>,
}

/// Setup for a repository created by a repository rule (http_archive, git_repository, etc.)
#[derive(
    Debug,
    derive_more::Display,
    Clone,
    Dupe,
    Allocative,
    PartialEq,
    Eq,
    Hash
)]
#[display("repository_rule({}, {})", repo_name, rule_name)]
pub struct RepositoryRuleCellSetup {
    /// The repository name (from the `name` attribute).
    pub repo_name: Arc<str>,
    /// The repository rule that created this (e.g., "http_archive").
    pub rule_name: Arc<str>,
    /// The path to the materialized repository content.
    pub source_path: Arc<str>,
}

/// Setup for a repository generated by a module extension that is pending materialization.
///
/// Extension-generated repos are created lazily: during extension evaluation, `RepoSpec`
/// objects are captured (no downloads). When the repo is first accessed, the `RepoSpec`
/// is executed to materialize the repository.
///
/// This cell origin is used for repos that haven't been materialized yet. After
/// materialization, the cell may be updated to point to the actual content.
#[derive(
    Debug,
    derive_more::Display,
    Clone,
    Dupe,
    Allocative,
    PartialEq,
    Eq,
    Hash
)]
#[display("extension_repo({}, {})", canonical_name, extension_id)]
pub struct ExtensionRepoCellSetup {
    /// Canonical repository name (e.g., "_main~pip~numpy").
    pub canonical_name: Arc<str>,
    /// Extension that generated this repo (e.g., "@@rules_python//pip:pip.bzl%pip").
    pub extension_id: Arc<str>,
    /// Internal name within the extension (e.g., "numpy").
    pub internal_name: Arc<str>,
    /// Hash of the RepoSpec for cache invalidation.
    pub spec_hash: Arc<str>,
    /// JSON-serialized RepoSpec for lazy execution.
    /// When the repo is first accessed, this is deserialized and used to
    /// create an ExtensionRepoExecutionKey for materialization.
    pub repo_spec_json: Arc<str>,
    /// Whether this repo has been materialized yet.
    /// When false, accessing the repo triggers lazy execution.
    pub materialized: bool,
}

#[derive(
    Debug,
    derive_more::Display,
    Clone,
    Dupe,
    allocative::Allocative,
    PartialEq,
    Eq,
    Hash
)]
#[display("git({}, {})", git_origin, commit)]
pub struct GitCellSetup {
    pub git_origin: Arc<str>,
    // Guaranteed to be a valid commit hash
    pub commit: Arc<str>,
    pub object_format: Option<GitObjectFormat>,
}

impl fmt::Display for ExternalCellOrigin {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Bundled(cell) => write!(f, "bundled({cell})"),
            Self::Git(git) => write!(f, "{git}"),
            Self::LocalPath(local) => {
                write!(f, "local_path({}, {})", local.module_name, local.path)
            }
            Self::Bzlmod(bzlmod) => write!(f, "{bzlmod}"),
            Self::RepositoryRule(repo) => write!(f, "{repo}"),
            Self::ExtensionRepo(ext_repo) => write!(f, "{ext_repo}"),
        }
    }
}

#[derive(Debug, Display, Eq, PartialEq, Clone, Dupe, Hash, Allocative)]
pub enum GitObjectFormat {
    #[display("sha1")]
    Sha1,
    #[display("sha256")]
    Sha256,
}

impl FromStr for GitObjectFormat {
    type Err = kuro_error::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "sha1" => Ok(GitObjectFormat::Sha1),
            "sha256" => Ok(GitObjectFormat::Sha256),
            _ => Err(kuro_error!(
                kuro_error::ErrorTag::Input,
                "object_format must be one of `sha1` or `sha256` (got: {})",
                &s,
            )),
        }
    }
}

impl GitObjectFormat {
    pub fn check(&self, s: &str) -> Result<(), kuro_error::Error> {
        match self {
            Self::Sha1 => {
                if s.len() == 40 && s.chars().all(|c| c.is_ascii_hexdigit()) {
                    Ok(())
                } else {
                    Err(kuro_error!(
                        kuro_error::ErrorTag::Input,
                        "not a valid SHA1 digest (got: {})",
                        &s,
                    ))
                }
            }
            Self::Sha256 => {
                if s.len() == 64 && s.chars().all(|c| c.is_ascii_hexdigit()) {
                    Ok(())
                } else {
                    Err(kuro_error!(
                        kuro_error::ErrorTag::Input,
                        "not a valid SHA256 digest (got: {})",
                        &s,
                    ))
                }
            }
        }
    }
}
