load(
    ":defs.bzl",
    "actionless_toolchain_impl",
    "demo_toolchain_impl",
    "dependency_rule",
    "root_rule",
    "string_setting",
    "transitioned_rule",
)

string_setting(
    name = "setting",
    build_setting_default = "default",
)

platform(name = "platform")
toolchain_type(name = "demo_type")
demo_toolchain_impl(name = "demo_impl", marker = "demo")
toolchain(
    name = "demo_toolchain",
    toolchain = ":demo_impl",
    toolchain_type = ":demo_type",
)
toolchain_type(name = "transition_type")
actionless_toolchain_impl(name = "transition_impl", marker = "transition")
toolchain(
    name = "transition_toolchain",
    toolchain = ":transition_impl",
    toolchain_type = ":transition_type",
)

dependency_rule(name = "shared")
dependency_rule(name = "left", deps = [":shared"])
dependency_rule(name = "right", deps = [":shared"])
dependency_rule(name = "aliased_owner")
alias(name = "aliased", actual = ":aliased_owner")
dependency_rule(name = "producer", out = "producer.out")
transitioned_rule(name = "transitioned")
root_rule(
    name = "root",
    aliased = ":aliased",
    deps = [":left", ":right"],
    generated = ":producer.out",
    transitioned = ":transitioned",
)
