load("@rules_rust//rust:defs.bzl", "rust_library")
load("@slug_crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "slug_server_v2",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    edition = crate_edition(),
    deps = all_crate_deps(normal = True) + [
        "//app/slug_analysis_v2",
        "//app/slug_build_api_v2",
        "//app/slug_bzlmod_v2",
        "//app/slug_core_v2",
        "//app/slug_identity_v2",
        "//app/slug_loading_v2",
        "//app/slug_query_v2",
        "//app/slug_reapi_v2",
    ],
    proc_macro_deps = all_crate_deps(proc_macro = True),
)
