/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the above-listed
 * licenses.
 */

//! Cell registration for extension-generated repositories.
//!
//! This module provides infrastructure to register repositories created by module
//! extensions as "pending" cells that will be materialized lazily when first accessed.
//!
//! ## How It Works
//!
//! 1. Extension evaluation captures `RepoSpec` objects (no downloads)
//! 2. `ModuleExtensionResult` contains canonical names for each repo
//! 3. This module creates cell definitions for each repo
//! 4. When a repo is accessed, the cell resolver detects it's pending and triggers
//!    lazy execution via `ExtensionRepoExecutionKey`
//!
//! ## Naming Convention
//!
//! - **Canonical name**: `_main+{extension_name}+{internal_name}` for root-owned
//!   extensions, or `{module}++{extension_name}+{internal_name}` for non-root
//!   module-owned extensions.
//!   - Example: `rules_python++pip+numpy` (Bazel 9.0 uses `+` separator)
//! - **Apparent name**: From `use_repo()` - maps to canonical
//!   - Example: `use_repo(pip, "numpy")` -> `@numpy` resolves to `@@rules_python++pip+numpy`
//!
//! ## Integration
//!
//! The cell definitions and aliases generated here are passed to `CellsAggregator`
//! in slug_common during cell resolver construction.

use crate::extension_execution_dice::ModuleExtensionResult;
use crate::extension_execution_dice::extension_repo_prefix;
use crate::extensions::canonical_extension_id_for_usage;
use crate::repo_spec::RepoSpec;
use crate::repository_invocations::AttrValue;
use crate::types::ExtensionUsage;
use crate::types::ParsedModuleFile;
use crate::types::TagValue;
use crate::types::UseRepo;
use std::collections::HashMap;

/// A pending repository cell definition.
///
/// This represents a repository generated by a module extension that will
/// be materialized lazily when first accessed.
#[derive(Debug, Clone)]
pub struct PendingRepoCell {
    /// Canonical repository name (e.g., "rules_python++pip+numpy").
    pub canonical_name: String,
    /// Extension that generated this repo (e.g., "@@rules_python//pip:pip.bzl%pip").
    pub extension_id: String,
    /// Internal name within the extension (e.g., "numpy").
    pub internal_name: String,
    /// Hash of the RepoSpec for cache invalidation.
    pub spec_hash: String,
    /// JSON-serialized RepoSpec for lazy execution.
    pub repo_spec_json: String,
    /// Project-relative path where the repo will be materialized.
    pub path: String,
}

/// An alias from apparent name to canonical name.
#[derive(Debug, Clone)]
pub struct RepoAlias {
    /// The apparent name (e.g., "numpy" from `use_repo(pip, "numpy")`).
    pub apparent_name: String,
    /// The canonical name this resolves to (e.g., "rules_python++pip+numpy").
    pub canonical_name: String,
    /// The module whose MODULE.bazel declared the `use_repo()` import.
    ///
    /// Bazel scopes apparent repo names to the declaring module, not to the
    /// module that owns the extension implementation. For example, if the
    /// `llvm` module imports a repo generated by `@tar.bzl`'s `toolchains`
    /// extension, labels inside `@llvm` must resolve `@bsd_tar_toolchains_*`
    /// through the `llvm` module's imports.
    pub declaring_module: Option<String>,
}

fn collect_root_extension_repo_overrides(
    parsed_modules: &[(String, ParsedModuleFile)],
    root_module_name: &str,
    ignore_dev_dependency: bool,
) -> std::collections::HashMap<(String, String), String> {
    let mut overrides = std::collections::HashMap::new();
    if ignore_dev_dependency {
        return overrides;
    }

    for (cell_name, parsed) in parsed_modules {
        let module_name = if parsed.module.name.is_empty() {
            root_module_name
        } else {
            &parsed.module.name
        };
        let is_root = cell_name == root_module_name
            || cell_name == "_main"
            || parsed.module.name == root_module_name;
        if !is_root {
            continue;
        }

        for usage in &parsed.extension_usages {
            let ext_id = canonical_extension_id_for_usage(usage, module_name);
            for (repo_name, dep_name) in &usage.repo_overrides {
                overrides.insert((ext_id.clone(), repo_name.clone()), dep_name.clone());
            }
            for (repo_name, dep_name) in &usage.injected_repos {
                overrides.insert((ext_id.clone(), repo_name.clone()), dep_name.clone());
            }
        }
    }

    overrides
}

fn canonical_repo_for_extension_import_with_root_overrides(
    usage: &ExtensionUsage,
    extension_repo_prefix: &str,
    internal_name: &str,
    root_override: Option<&String>,
    use_usage_overrides: bool,
) -> crate::repo_mapping::ExtensionImportCanonicalization {
    if let Some(dep_repo) = root_override {
        return crate::repo_mapping::ExtensionImportCanonicalization {
            canonical_name: crate::repo_mapping::CanonicalRepoName::new(dep_repo.clone()),
            is_override: true,
        };
    }

    crate::repo_mapping::canonical_repo_for_extension_import_with_usage_overrides(
        usage,
        extension_repo_prefix,
        internal_name,
        use_usage_overrides,
    )
}

/// Cell definitions to register from extension execution.
///
/// Contains cells (with canonical names) and aliases (from use_repo).
#[derive(Debug, Clone, Default)]
pub struct ExtensionCellDefinitions {
    /// Pending repository cells.
    pub cells: Vec<PendingRepoCell>,
    /// Cell aliases: apparent name -> canonical name.
    pub aliases: Vec<RepoAlias>,
}

impl ExtensionCellDefinitions {
    /// Create empty definitions.
    pub fn new() -> Self {
        Self::default()
    }

    /// Check if there are any definitions.
    pub fn is_empty(&self) -> bool {
        self.cells.is_empty() && self.aliases.is_empty()
    }

    /// Number of cells defined.
    pub fn cell_count(&self) -> usize {
        self.cells.len()
    }

    /// Number of aliases defined.
    pub fn alias_count(&self) -> usize {
        self.aliases.len()
    }

    /// Merge with another set of definitions.
    pub fn merge(&mut self, other: ExtensionCellDefinitions) {
        self.cells.extend(other.cells);
        self.aliases.extend(other.aliases);
    }
}

/// Pre-compute extension repo cells from `use_repo()` declarations alone.
///
/// This is the Bazel 9.0-compatible approach: canonical names are deterministically
/// computed from the module graph topology (MODULE.bazel `use_extension()` +
/// `use_repo()` declarations) WITHOUT executing any extensions or consulting the lockfile.
///
/// Formula: `_main+{extension_name}+{repo_name}` for root-owned extensions and
/// `{owner_module}++{extension_name}+{repo_name}` for dependency-owned
/// extensions, where `extension_name` is extracted from the extension ID (after
/// the `%`).
///
/// # Arguments
/// * `parsed_modules` - All parsed MODULE.bazel files (module_name, parsed)
/// * `root_module_name` - Name of the root module (or "_main" if unnamed)
///
/// # Returns
/// (cells, aliases) ready for cell resolver registration.
pub fn pre_compute_extension_repo_cells(
    parsed_modules: &[(String, ParsedModuleFile)],
    root_module_name: &str,
    ignore_dev_dependency: bool,
    extension_unique_names: Option<&HashMap<String, String>>,
) -> slug_error::Result<(Vec<PendingRepoCell>, Vec<RepoAlias>)> {
    let mut cells = Vec::new();
    let mut aliases = Vec::new();
    // Track which canonical names we've already registered to avoid duplicates
    // (same repo may appear in use_repo() from multiple modules).
    let mut seen_canonical: std::collections::HashSet<String> = std::collections::HashSet::new();
    let root_repo_overrides = collect_root_extension_repo_overrides(
        parsed_modules,
        root_module_name,
        ignore_dev_dependency,
    );

    for (cell_name, parsed) in parsed_modules {
        // Use the module's own name from its MODULE.bazel for canonical naming.
        // For the root module, this matches root_module_name.
        // For transitive deps (e.g., bazel_features), this uses their declared name,
        // not the cell name (which includes a version suffix like "bazel_features+1.28.0").
        let module_name = if parsed.module.name.is_empty() {
            root_module_name
        } else {
            &parsed.module.name
        };

        let is_root = cell_name == root_module_name
            || cell_name == "_main"
            || parsed.module.name == root_module_name;

        for usage in &parsed.extension_usages {
            // Skip dev_dependency usages from non-root modules (Bazel 9.0 behavior)
            if usage.dev_dependency && (!is_root || ignore_dev_dependency) {
                tracing::debug!(
                    "Skipping dev_dependency extension repo cells for '{}' from non-root module '{}'",
                    usage.extension_id(),
                    cell_name
                );
                continue;
            }
            // Match the canonical form used by `aggregate_extensions_with_root`
            // so DICE extension-spoke lookup finds the aggregation for this
            // setup. See `extensions::canonical_extension_id`.
            let ext_id = canonical_extension_id_for_usage(usage, module_name);
            let repo_prefix = extension_unique_names
                .and_then(|m| m.get(&ext_id).cloned())
                .unwrap_or_else(|| extension_repo_prefix(&ext_id, root_module_name));

            // The canonical name prefix is the module that OWNS the .bzl file, not
            // the module that uses the extension. For `@bazel_features//private:ext.bzl`,
            // the owning module prefix is `bazel_features+`. For `//local:ext.bzl`,
            // it's `_main`.
            //
            // Bazel convention: the root module uses `_main` as its canonical prefix
            // (regardless of its declared name, which is only used by OTHER modules
            // to reference it). Extensions defined in the root module's own .bzl files
            // therefore produce repos like `_main+ext_name+repo_name`, or
            // Bazel's isolated `_main+_ext+++usage+repo_name` shape.
            // Use the canonical `ext_id` (e.g. `@rules_java//java:extensions.bzl%toolchains`)
            // here, NOT `usage.extension_bzl_file` (e.g. `//java:extensions.bzl`).
            // `extract_owning_module` reads the `@<module>//` prefix; a bare
            // `//` path has no prefix and falls back to `_main`, which would
            // mis-attribute every transitive dep's relative `use_extension`
            // to the root module.
            let extracted_owner = extract_owning_module(&ext_id, root_module_name);
            let owner_module = if is_root && extracted_owner == module_name {
                "_main".to_owned()
            } else {
                extracted_owner
            };

            if is_root && !ignore_dev_dependency {
                // `override_repo(ext, generated = "actual_dep")` replaces the
                // extension's repo named `generated` with the selected bzlmod
                // dependency `actual_dep`. That replacement is visible from
                // repos owned by the extension even when the root module does not
                // also import the generated repo with `use_repo()`.
                for (repo_name, dep_name) in &usage.repo_overrides {
                    aliases.push(RepoAlias {
                        apparent_name: repo_name.clone(),
                        canonical_name: dep_name.clone(),
                        declaring_module: Some(owner_module.clone()),
                    });
                    aliases.push(RepoAlias {
                        apparent_name: format!("{}+{}", repo_prefix, repo_name),
                        canonical_name: dep_name.clone(),
                        declaring_module: None,
                    });
                }
                for (repo_name, dep_name) in &usage.injected_repos {
                    aliases.push(RepoAlias {
                        apparent_name: repo_name.clone(),
                        canonical_name: dep_name.clone(),
                        declaring_module: Some(owner_module.clone()),
                    });
                    aliases.push(RepoAlias {
                        apparent_name: format!("{}+{}", repo_prefix, repo_name),
                        canonical_name: dep_name.clone(),
                        declaring_module: None,
                    });
                }
            }

            for import in &usage.imports {
                // Positional repos: use_repo(ext, "numpy", "requests")
                for repo_name in &import.repos {
                    let canonical = canonical_repo_for_extension_import_with_root_overrides(
                        usage,
                        &repo_prefix,
                        repo_name,
                        root_repo_overrides.get(&(ext_id.clone(), repo_name.clone())),
                        is_root,
                    );
                    let is_override = canonical.is_override;
                    let canonical = canonical.canonical_name.into_string();

                    if !is_override && seen_canonical.insert(canonical.clone()) {
                        let path = format!("bazel-external/{}", canonical);
                        cells.push(PendingRepoCell {
                            canonical_name: canonical.clone(),
                            extension_id: ext_id.clone(),
                            internal_name: repo_name.clone(),
                            spec_hash: String::new(), // Filled in after extension execution
                            repo_spec_json: String::new(), // Filled in after extension execution
                            path,
                        });
                    }

                    // Alias: apparent name -> canonical name
                    if repo_name.as_str() != canonical {
                        aliases.push(RepoAlias {
                            apparent_name: repo_name.clone(),
                            canonical_name: canonical,
                            declaring_module: Some(module_name.to_owned()),
                        });
                    }
                }

                // Keyword repos: use_repo(ext, myname = "actual_repo")
                for (apparent_name, actual_name) in &import.repo_mapping {
                    let canonical = canonical_repo_for_extension_import_with_root_overrides(
                        usage,
                        &repo_prefix,
                        actual_name,
                        root_repo_overrides.get(&(ext_id.clone(), actual_name.clone())),
                        is_root,
                    );
                    let is_override = canonical.is_override;
                    let canonical = canonical.canonical_name.into_string();

                    if !is_override && seen_canonical.insert(canonical.clone()) {
                        let path = format!("bazel-external/{}", canonical);
                        cells.push(PendingRepoCell {
                            canonical_name: canonical.clone(),
                            extension_id: ext_id.clone(),
                            internal_name: actual_name.clone(),
                            spec_hash: String::new(),
                            repo_spec_json: String::new(),
                            path,
                        });
                    }

                    // Alias: apparent_name -> canonical
                    aliases.push(RepoAlias {
                        apparent_name: apparent_name.clone(),
                        canonical_name: canonical,
                        declaring_module: Some(module_name.to_owned()),
                    });
                }
            }
        }
    }

    // Also register use_repo_rule() invocations as extension cells.
    // In Bazel, use_repo_rule() creates implicit single-repo extensions.
    // The apparent repo name is the invocation's `name`, while the canonical
    // repo name includes the owning module and repo-rule name.
    for (cell_name, parsed) in parsed_modules {
        let module_name = if parsed.module.name.is_empty() {
            root_module_name
        } else {
            &parsed.module.name
        };
        let is_root = cell_name == root_module_name
            || cell_name == "_main"
            || parsed.module.name == root_module_name;

        for invocation in &parsed.repo_rule_invocations {
            if invocation.dev_dependency && (!is_root || ignore_dev_dependency) {
                tracing::debug!(
                    "Skipping dev_dependency repo rule '{}' from module '{}'",
                    invocation.name,
                    cell_name
                );
                continue;
            }
            let canonical = canonicalize_repo_rule_invocation_name(
                module_name,
                is_root,
                &invocation.rule_source,
                &invocation.name,
            );
            if seen_canonical.insert(canonical.clone()) {
                let path = format!("bazel-external/{}", canonical);
                // Serialize the invocation attrs into a RepoSpec so the normal
                // cached-spec materialization path handles them (preserves defaults
                // via repo rule definition lookup downstream).
                let rule_source =
                    canonicalize_repo_rule_source(&invocation.rule_source, module_name, is_root);
                let mut spec = RepoSpec::new(rule_source.clone());
                spec.local = repo_rule_source_is_builtin_local(&rule_source);
                for (k, v) in &invocation.attrs {
                    spec.attributes
                        .insert(k.clone(), tag_value_to_attr_value(v));
                }
                let spec_hash = spec.compute_hash();
                let repo_spec_json = serde_json::to_string(&spec).unwrap_or_default();
                cells.push(PendingRepoCell {
                    canonical_name: canonical.clone(),
                    extension_id: rule_source,
                    internal_name: invocation.name.clone(),
                    spec_hash,
                    repo_spec_json,
                    path,
                });
            }
            if invocation.name != canonical {
                aliases.push(RepoAlias {
                    apparent_name: invocation.name.clone(),
                    canonical_name: canonical,
                    declaring_module: Some(module_name.to_owned()),
                });
            }
        }
    }

    slug_util::memory_checkpoint::checkpoint(
        "bzlmod_pre_compute_extension_repo_cells",
        [
            ("parsed_modules", parsed_modules.len()),
            ("cells", cells.len()),
            ("aliases", aliases.len()),
        ],
    );
    tracing::info!(
        "Pre-computed {} extension repo cell(s) and {} alias(es) from use_repo()/use_repo_rule() declarations",
        cells.len(),
        aliases.len()
    );

    Ok((cells, aliases))
}

fn canonicalize_repo_rule_invocation_name(
    module_name: &str,
    is_root: bool,
    rule_source: &str,
    repo_name: &str,
) -> String {
    let Some((_, rule_name)) = rule_source.rsplit_once('%') else {
        return repo_name.to_owned();
    };
    if is_root {
        format!("+{}+{}", rule_name, repo_name)
    } else {
        format!("{}++{}+{}", module_name, rule_name, repo_name)
    }
}

fn canonicalize_repo_rule_source(rule_source: &str, module_name: &str, is_root: bool) -> String {
    let Some((bzl_file, rule_name)) = rule_source.rsplit_once('%') else {
        return rule_source.to_owned();
    };

    let resolved = if !is_root {
        if bzl_file.starts_with("//") {
            format!("@{}{}", module_name, bzl_file)
        } else if let Some(rest) = bzl_file.strip_prefix(':') {
            format!("@{}//:{}", module_name, rest)
        } else {
            bzl_file.to_owned()
        }
    } else if let Some(rest) = bzl_file.strip_prefix(':') {
        format!("//:{}", rest)
    } else {
        bzl_file.to_owned()
    };

    format!("{resolved}%{rule_name}")
}

fn repo_rule_source_is_builtin_local(rule_source: &str) -> bool {
    let Some((bzl_file, rule_name)) = rule_source.rsplit_once('%') else {
        return false;
    };
    if !matches!(rule_name, "local_repository" | "new_local_repository") {
        return false;
    }

    let normalized_bzl_file = bzl_file
        .strip_prefix("@@")
        .or_else(|| bzl_file.strip_prefix('@'))
        .unwrap_or(bzl_file);
    normalized_bzl_file == "bazel_tools//tools/build_defs/repo:local.bzl"
}

/// Convert a MODULE.bazel `TagValue` (parser representation) to an `AttrValue`
/// (serialized RepoSpec representation).
fn tag_value_to_attr_value(tv: &TagValue) -> AttrValue {
    match tv {
        TagValue::String(s) => {
            if s.starts_with("//") || s.starts_with('@') || s.starts_with(':') {
                AttrValue::Label(s.clone())
            } else {
                AttrValue::String(s.clone())
            }
        }
        TagValue::Int(i) => AttrValue::Int(*i),
        TagValue::Bool(b) => AttrValue::Bool(*b),
        TagValue::None => AttrValue::None,
        TagValue::Label(s) => AttrValue::Label(s.clone()),
        TagValue::List(items) => {
            let strings: Vec<String> = items
                .iter()
                .filter_map(|v| match v {
                    TagValue::String(s) | TagValue::Label(s) => Some(s.clone()),
                    _ => None,
                })
                .collect();
            AttrValue::StringList(strings)
        }
        TagValue::Dict(entries) => {
            let map: indexmap::IndexMap<String, AttrValue> = entries
                .iter()
                .map(|(k, v)| (k.clone(), tag_value_to_attr_value(v)))
                .collect();
            AttrValue::Dict(map)
        }
    }
}

/// Extract the owning module name from an extension bzl file path.
///
/// In Bazel, the canonical name prefix for extension repos is the canonical
/// repo name of the module that *owns* the .bzl file, not the module that calls
/// `use_extension()`.
/// - root-owned extensions use `_main`
/// - dependency-owned extensions preserve Bazel 9's trailing module separator,
///   so `@bazel_features//private:extensions.bzl` becomes `bazel_features+`
fn extract_owning_module(extension_bzl_file: &str, current_module: &str) -> String {
    if let Some(rest) = extension_bzl_file.strip_prefix('@') {
        // @module_name//path:file.bzl → module_name
        if let Some(pos) = rest.find("//") {
            let module_name = &rest[..pos];
            if !module_name.is_empty() {
                if !current_module.is_empty() && module_name == current_module {
                    return "_main".to_owned();
                }
                if module_name.ends_with('+') {
                    return module_name.to_owned();
                }
                return format!("{module_name}+");
            }
        }
    }
    "_main".to_owned()
}

/// Build cell definitions from a module extension result.
///
/// This creates:
/// 1. A cell for each generated repository with its canonical name
/// 2. A project-relative path at `bazel-external/{canonical_name}`
/// 3. Metadata for lazy materialization
/// 4. Serialized RepoSpec for lazy execution
///
/// # Arguments
/// * `result` - The module extension execution result
///
/// # Returns
/// Cell definitions ready to be passed to `CellsAggregator`.
pub fn build_extension_cells(
    result: &ModuleExtensionResult,
) -> slug_error::Result<ExtensionCellDefinitions> {
    let mut defs = ExtensionCellDefinitions::new();

    // Sort by internal name — HashMap/FxHashMap iteration order is
    // insertion-order-dependent under hashbrown, and the downstream cell
    // aggregator dedups by first-seen CellName. Without sort, warm
    // invocations pick different winners for cells registered by
    // multiple extensions (Plan 21.2).
    let mut specs: Vec<_> = result.generated_repo_specs.iter().collect();
    specs.sort_by(|a, b| a.0.cmp(b.0));
    for (internal_name, repo_spec) in specs {
        let canonical = result.canonical_name(internal_name).ok_or_else(|| {
            slug_error::slug_error!(
                slug_error::ErrorTag::Input,
                "Missing canonical name for repo '{}'",
                internal_name
            )
        })?;

        // Path: bazel-external/{canonical_name}
        let path = format!("bazel-external/{}", canonical);

        // Serialize RepoSpec to JSON for lazy execution
        let repo_spec_json = serde_json::to_string(repo_spec).map_err(|e| {
            slug_error::slug_error!(
                slug_error::ErrorTag::Input,
                "Failed to serialize RepoSpec for repo '{}': {}",
                internal_name,
                e
            )
        })?;

        let cell = PendingRepoCell {
            canonical_name: canonical.to_owned(),
            extension_id: result.extension_id.to_string(),
            internal_name: internal_name.clone(),
            spec_hash: repo_spec.compute_hash(),
            repo_spec_json,
            path,
        };

        defs.cells.push(cell);
    }

    Ok(defs)
}

/// Build cell aliases from use_repo() declarations.
///
/// This creates aliases so that apparent names from `use_repo()` resolve
/// to the canonical cell names.
///
/// # Example
/// `use_repo(pip, "numpy")` creates alias `numpy` -> `rules_python++pip+numpy`
/// `use_repo(pip, myname = "numpy")` creates alias `myname` -> `rules_python++pip+numpy`
///
/// # Arguments
/// * `extension_result` - The extension result with canonical name mappings
/// * `use_repos` - The use_repo() declarations from MODULE.bazel
///
/// # Returns
/// Aliases to add to the cell definitions.
pub fn build_use_repo_aliases(
    extension_result: &ModuleExtensionResult,
    use_repos: &[UseRepo],
) -> slug_error::Result<Vec<RepoAlias>> {
    let mut aliases = Vec::new();

    for use_repo in use_repos {
        // Handle positional repo names: use_repo(ext, "repo1", "repo2")
        // These create aliases where apparent name == internal name
        for repo_name in &use_repo.repos {
            if let Some(canonical) = extension_result.canonical_name(repo_name) {
                // Don't create alias if apparent name equals canonical name
                if repo_name != canonical {
                    aliases.push(RepoAlias {
                        apparent_name: repo_name.clone(),
                        canonical_name: canonical.to_owned(),
                        declaring_module: None,
                    });
                }
            } else {
                // Repo not found in extension result - this is likely a configuration error
                // where use_repo references a repo that the extension didn't create
                tracing::warn!(
                    "use_repo references '{}' but it wasn't generated by extension '{}' - check that the extension creates this repo",
                    repo_name,
                    extension_result.extension_id
                );
            }
        }

        // Handle keyword repo mappings: use_repo(ext, myname = "actual_repo")
        // apparent_name (myname) -> canonical_name of actual_repo
        for (apparent_name, actual_name) in &use_repo.repo_mapping {
            if let Some(canonical) = extension_result.canonical_name(actual_name) {
                aliases.push(RepoAlias {
                    apparent_name: apparent_name.clone(),
                    canonical_name: canonical.to_owned(),
                    declaring_module: None,
                });
            } else {
                tracing::warn!(
                    "use_repo mapping '{}' -> '{}' not found in extension '{}' - check that the extension creates repo '{}'",
                    apparent_name,
                    actual_name,
                    extension_result.extension_id,
                    actual_name
                );
            }
        }
    }

    Ok(aliases)
}

/// Build complete cell definitions from extension result and use_repo declarations.
///
/// This is the main entry point that combines:
/// 1. Cell definitions for all generated repos
/// 2. Aliases from all use_repo() declarations
///
/// # Arguments
/// * `result` - The module extension execution result
/// * `use_repos` - All use_repo() declarations for this extension
///
/// # Returns
/// Complete cell definitions ready for `CellsAggregator`.
pub fn build_extension_cell_definitions(
    result: &ModuleExtensionResult,
    use_repos: &[UseRepo],
) -> slug_error::Result<ExtensionCellDefinitions> {
    let mut defs = build_extension_cells(result)?;
    let aliases = build_use_repo_aliases(result, use_repos)?;
    defs.aliases.extend(aliases);
    Ok(defs)
}

/// Build cell definitions from multiple extension results.
///
/// This aggregates results from all extensions into a single set of
/// cell definitions.
///
/// # Arguments
/// * `extension_results` - Map from extension_id to (result, use_repos)
///
/// # Returns
/// Merged cell definitions for all extensions.
pub fn build_all_extension_cells(
    extension_results: &fxhash::FxHashMap<String, (ModuleExtensionResult, Vec<UseRepo>)>,
) -> slug_error::Result<ExtensionCellDefinitions> {
    let mut all_defs = ExtensionCellDefinitions::new();

    // Sort by extension id — FxHashMap iteration is insertion-order-
    // dependent under hashbrown, and the downstream CellName dedup is
    // first-wins, so without sort the winner flips across warm
    // invocations (Plan 21.2).
    let mut sorted: Vec<_> = extension_results.iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(b.0));
    for (extension_id, (result, use_repos)) in sorted {
        match build_extension_cell_definitions(result, use_repos) {
            Ok(defs) => {
                tracing::info!(
                    "Extension '{}' registered {} cells, {} aliases",
                    extension_id,
                    defs.cell_count(),
                    defs.alias_count()
                );
                all_defs.merge(defs);
            }
            Err(e) => {
                tracing::warn!(
                    "Failed to build cell definitions for extension '{}': {}",
                    extension_id,
                    e
                );
                return Err(e);
            }
        }
    }

    slug_util::memory_checkpoint::checkpoint(
        "bzlmod_build_all_extension_cells",
        [
            ("extensions", extension_results.len()),
            ("cells", all_defs.cell_count()),
            ("aliases", all_defs.alias_count()),
        ],
    );
    Ok(all_defs)
}

/// Extract use_repo declarations for a specific extension from extension usages.
///
/// This filters the use_repo declarations to only those for the given extension.
pub fn extract_use_repos_for_extension<'a>(
    extension_id: &str,
    extension_usages: &'a [ExtensionUsage],
) -> Vec<&'a UseRepo> {
    extension_usages
        .iter()
        .filter(|usage| usage.extension_id() == extension_id)
        .flat_map(|usage| usage.imports.iter())
        .collect()
}

/// Check if a cell name looks like an extension-generated canonical name.
///
/// Extension repos have canonical names like `_main+extension+repo` or
/// `module++extension+repo` (Bazel 9.0 `+` separator).
/// Also accepts legacy `~` separator for backwards compatibility.
pub fn is_extension_repo_canonical_name(name: &str) -> bool {
    // Bazel 9.0 uses + separator: <module>+<extension>+<repo>
    let parts_plus: Vec<_> = name.split('+').collect();
    if parts_plus.len() >= 3 {
        return true;
    }
    // Also accept legacy ~ separator for backwards compatibility
    let parts_tilde: Vec<_> = name.split('~').collect();
    parts_tilde.len() >= 3
}

/// Parse an extension canonical name into components.
///
/// # Returns
/// `Some((prefix, extension_name, internal_name))` if valid, `None` otherwise.
///
/// # Example
/// `rules_python++pip+numpy` -> `Some(("rules_python+", "pip", "numpy"))`
pub fn parse_canonical_name(canonical: &str) -> Option<(&str, &str, &str)> {
    // Try + separator first (Bazel 9.0), then ~ for backwards compat
    if let Some((owner, rest)) = canonical.split_once("++") {
        let (extension, internal) = rest.split_once('+')?;
        return Some((&canonical[..owner.len() + 1], extension, internal));
    }
    let parts: Vec<_> = canonical.splitn(3, '+').collect();
    if parts.len() == 3 {
        return Some((parts[0], parts[1], parts[2]));
    }
    let parts: Vec<_> = canonical.splitn(3, '~').collect();
    if parts.len() == 3 {
        Some((parts[0], parts[1], parts[2]))
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;
    use std::sync::Arc;

    use super::*;
    use crate::globals::RepoRuleInvocation;
    use crate::repo_spec::RepoSpec;
    use crate::repository_invocations::AttrValue;
    use crate::types::Module;
    use crate::version::Version;

    fn parsed_module(name: &str) -> ParsedModuleFile {
        ParsedModuleFile {
            module: Module::new(name.to_owned(), Version::empty()),
            has_module_directive: true,
            extension_usages: Vec::new(),
            repo_rule_invocations: Vec::new(),
            registered_toolchains: Vec::new(),
            registered_execution_platforms: Vec::new(),
        }
    }

    fn make_test_result() -> ModuleExtensionResult {
        let mut specs = fxhash::FxHashMap::default();
        specs.insert(
            "numpy".to_owned(),
            RepoSpec::new("@@rules_python//pip:pip.bzl%pip_install".to_owned())
                .with_attr("version".to_owned(), AttrValue::String("1.24.0".to_owned())),
        );
        specs.insert(
            "requests".to_owned(),
            RepoSpec::new("@@rules_python//pip:pip.bzl%pip_install".to_owned())
                .with_attr("version".to_owned(), AttrValue::String("2.31.0".to_owned())),
        );

        ModuleExtensionResult::new(
            Arc::from("@@rules_python//pip:pip.bzl%pip"),
            "sha256-test".to_owned(),
            specs,
            "",
        )
    }

    #[test]
    fn test_build_extension_cells() {
        let result = make_test_result();
        let defs = build_extension_cells(&result).unwrap();

        assert_eq!(defs.cell_count(), 2);
        assert_eq!(defs.alias_count(), 0); // No aliases from this function

        // Check cell names are canonical
        let cell_names: Vec<_> = defs
            .cells
            .iter()
            .map(|c| c.canonical_name.as_str())
            .collect();
        assert!(cell_names.contains(&"rules_python++pip+numpy"));
        assert!(cell_names.contains(&"rules_python++pip+requests"));

        // Check paths
        for cell in &defs.cells {
            assert!(cell.path.starts_with("bazel-external/rules_python++pip+"));
        }

        // Check extension IDs
        for cell in &defs.cells {
            assert_eq!(cell.extension_id, "@@rules_python//pip:pip.bzl%pip");
        }
    }

    #[test]
    fn test_canonicalize_repo_rule_source_for_dependency_module() {
        assert_eq!(
            canonicalize_repo_rule_source(
                "//toolchain/local/triplet:defs.bzl%toolchain_local_triplet",
                "toolchain_utils",
                false,
            ),
            "@toolchain_utils//toolchain/local/triplet:defs.bzl%toolchain_local_triplet",
        );
        assert_eq!(
            canonicalize_repo_rule_source(":extensions.bzl%maven", "rules_jvm_external", false),
            "@rules_jvm_external//:extensions.bzl%maven",
        );
    }

    #[test]
    fn test_canonicalize_repo_rule_source_keeps_root_relative() {
        assert_eq!(
            canonicalize_repo_rule_source("//:rbe.bzl%rbe_platform_repository", "zeromatter", true),
            "//:rbe.bzl%rbe_platform_repository",
        );
        assert_eq!(
            canonicalize_repo_rule_source(":rbe.bzl%rbe_platform_repository", "zeromatter", true),
            "//:rbe.bzl%rbe_platform_repository",
        );
    }

    #[test]
    fn test_canonicalize_repo_rule_invocation_name_matches_bazel_root_shape() {
        assert_eq!(
            canonicalize_repo_rule_invocation_name(
                "zeromatter",
                true,
                "//:repo.bzl%rr",
                "launcher"
            ),
            "+rr+launcher",
        );
    }

    #[test]
    fn test_canonicalize_repo_rule_invocation_name_matches_bazel_non_root_shape() {
        assert_eq!(
            canonicalize_repo_rule_invocation_name(
                "llvm",
                false,
                "//extensions:llvm.bzl%llvm",
                "llvm-project"
            ),
            "llvm++llvm+llvm-project",
        );
    }

    #[test]
    fn test_precompute_use_repo_rule_uses_canonical_name_and_apparent_alias() {
        let mut module = parsed_module("ape");
        let mut attrs = indexmap::IndexMap::new();
        attrs.insert(
            "url".to_owned(),
            crate::types::TagValue::String("https://example.invalid/tool".to_owned()),
        );
        module.repo_rule_invocations.push(RepoRuleInvocation {
            name: "launcher".to_owned(),
            rule_source: "@toolchain_utils//toolchain/local/select:defs.bzl%toolchain_local_select"
                .to_owned(),
            dev_dependency: false,
            attrs,
        });

        let (cells, aliases) = pre_compute_extension_repo_cells(
            &[("ape+1.0.1".to_owned(), module)],
            "zeromatter",
            false,
            None,
        )
        .unwrap();

        assert_eq!(cells.len(), 1);
        assert_eq!(
            cells[0].canonical_name,
            "ape++toolchain_local_select+launcher"
        );
        assert_eq!(cells[0].internal_name, "launcher");
        assert_eq!(
            cells[0].path,
            "bazel-external/ape++toolchain_local_select+launcher"
        );
        let repo_spec: RepoSpec = serde_json::from_str(&cells[0].repo_spec_json).unwrap();
        assert_eq!(
            repo_spec.repo_rule_id,
            "@toolchain_utils//toolchain/local/select:defs.bzl%toolchain_local_select"
        );
        assert_eq!(
            repo_spec.attributes.get("url"),
            Some(&AttrValue::String(
                "https://example.invalid/tool".to_owned()
            ))
        );
        assert_eq!(aliases.len(), 1);
        assert_eq!(aliases[0].apparent_name, "launcher");
        assert_eq!(
            aliases[0].canonical_name,
            "ape++toolchain_local_select+launcher"
        );
    }

    #[test]
    fn test_precompute_use_repo_rule_marks_builtin_local_repos_local() {
        let mut module = parsed_module("ape");
        for rule_name in ["local_repository", "new_local_repository"] {
            let mut attrs = indexmap::IndexMap::new();
            attrs.insert(
                "path".to_owned(),
                crate::types::TagValue::String("repo_src".to_owned()),
            );
            if rule_name == "new_local_repository" {
                attrs.insert(
                    "build_file_content".to_owned(),
                    crate::types::TagValue::String("exports_files([\"data.txt\"])\n".to_owned()),
                );
            }
            module.repo_rule_invocations.push(RepoRuleInvocation {
                name: format!("{rule_name}_repo"),
                rule_source: format!("@bazel_tools//tools/build_defs/repo:local.bzl%{rule_name}"),
                dev_dependency: false,
                attrs,
            });
        }
        module.repo_rule_invocations.push(RepoRuleInvocation {
            name: "archive_repo".to_owned(),
            rule_source: "@bazel_tools//tools/build_defs/repo:http.bzl%http_archive".to_owned(),
            dev_dependency: false,
            attrs: indexmap::IndexMap::new(),
        });

        let (cells, _) =
            pre_compute_extension_repo_cells(&[("ape+1.0.1".to_owned(), module)], "ape", false, None)
                .unwrap();

        let local_specs: Vec<_> = cells
            .iter()
            .filter(|cell| cell.internal_name.ends_with("_repository_repo"))
            .map(|cell| serde_json::from_str::<RepoSpec>(&cell.repo_spec_json).unwrap())
            .collect();
        assert_eq!(local_specs.len(), 2);
        assert!(local_specs.iter().all(|spec| spec.local));

        let archive = cells
            .iter()
            .find(|cell| cell.internal_name == "archive_repo")
            .unwrap();
        let archive_spec: RepoSpec = serde_json::from_str(&archive.repo_spec_json).unwrap();
        assert!(!archive_spec.local);
    }

    #[test]
    fn test_precompute_dependency_use_repo_uses_bazel9_double_plus_canonical_name() {
        let mut module = parsed_module("bazel_lib");
        let mut usage = ExtensionUsage::new(
            "@bazel_lib//lib:extensions.bzl".to_owned(),
            "toolchains".to_owned(),
        );
        usage
            .imports
            .push(UseRepo::new().add_repo("expand_template_toolchains".to_owned()));
        module.extension_usages.push(usage);

        let (cells, aliases) = pre_compute_extension_repo_cells(
            &[("bazel_lib+3.2.2".to_owned(), module)],
            "zeromatter",
            false,
            None,
        )
        .unwrap();

        assert_eq!(cells.len(), 1);
        assert_eq!(
            cells[0].canonical_name,
            "bazel_lib++toolchains+expand_template_toolchains"
        );
        assert_eq!(
            cells[0].path,
            "bazel-external/bazel_lib++toolchains+expand_template_toolchains"
        );
        assert_eq!(aliases.len(), 1);
        assert_eq!(aliases[0].apparent_name, "expand_template_toolchains");
        assert_eq!(
            aliases[0].canonical_name,
            "bazel_lib++toolchains+expand_template_toolchains"
        );
        assert_eq!(aliases[0].declaring_module.as_deref(), Some("bazel_lib"));
    }

    #[test]
    fn test_precompute_use_repo_honors_override_repo() {
        let mut module = parsed_module("root");
        let mut usage =
            ExtensionUsage::new("@rules_owner//:extensions.bzl".to_owned(), "ext".to_owned());
        usage
            .imports
            .push(UseRepo::new().add_mapping("public".to_owned(), "generated".to_owned()));
        usage
            .repo_overrides
            .push(("generated".to_owned(), "actual_dep".to_owned()));
        module.extension_usages.push(usage);

        let (cells, aliases) =
            pre_compute_extension_repo_cells(&[("rules_owner".to_owned(), module)], "root", false, None)
                .unwrap();

        assert!(cells.is_empty());
        assert_eq!(aliases.len(), 3);
        assert_eq!(aliases[0].apparent_name, "generated");
        assert_eq!(aliases[0].canonical_name, "actual_dep");
        assert_eq!(aliases[0].declaring_module.as_deref(), Some("rules_owner+"));
        assert_eq!(aliases[1].apparent_name, "rules_owner++ext+generated");
        assert_eq!(aliases[1].canonical_name, "actual_dep");
        assert_eq!(aliases[1].declaring_module, None);
        assert_eq!(aliases[2].apparent_name, "public");
        assert_eq!(aliases[2].canonical_name, "actual_dep");
        assert_eq!(aliases[2].declaring_module.as_deref(), Some("root"));
    }

    #[test]
    fn test_precompute_use_repo_ignores_non_root_override_repo() {
        let mut module = parsed_module("rules_owner");
        let mut usage = ExtensionUsage::new("//:extensions.bzl".to_owned(), "ext".to_owned());
        usage
            .imports
            .push(UseRepo::new().add_mapping("public".to_owned(), "generated".to_owned()));
        usage
            .repo_overrides
            .push(("generated".to_owned(), "actual_dep".to_owned()));
        module.extension_usages.push(usage);

        let (cells, aliases) =
            pre_compute_extension_repo_cells(&[("rules_owner".to_owned(), module)], "root", false, None)
                .unwrap();

        assert_eq!(cells.len(), 1);
        assert_eq!(cells[0].canonical_name, "rules_owner++ext+generated");
        assert_eq!(aliases.len(), 1);
        assert_eq!(aliases[0].apparent_name, "public");
        assert_eq!(aliases[0].canonical_name, "rules_owner++ext+generated");
        assert_eq!(aliases[0].declaring_module.as_deref(), Some("rules_owner"));
    }

    #[test]
    fn test_root_override_repo_applies_to_owner_module_use_repo() {
        let mut root = parsed_module("root");
        let mut root_usage =
            ExtensionUsage::new("@rules_owner//:extensions.bzl".to_owned(), "ext".to_owned());
        root_usage
            .repo_overrides
            .push(("generated".to_owned(), "actual_dep".to_owned()));
        root.extension_usages.push(root_usage);

        let mut owner = parsed_module("rules_owner");
        let mut owner_usage = ExtensionUsage::new("//:extensions.bzl".to_owned(), "ext".to_owned());
        owner_usage
            .imports
            .push(UseRepo::new().add_repo("generated".to_owned()));
        owner.extension_usages.push(owner_usage);

        let (cells, aliases) = pre_compute_extension_repo_cells(
            &[("root".to_owned(), root), ("rules_owner".to_owned(), owner)],
            "root",
            false,
            None,
        )
        .unwrap();

        assert!(cells.is_empty());
        assert!(aliases.iter().any(|alias| {
            alias.apparent_name == "generated"
                && alias.canonical_name == "actual_dep"
                && alias.declaring_module.as_deref() == Some("rules_owner")
        }));
    }

    #[test]
    fn test_root_override_repo_ignored_under_ignore_dev_dependency() {
        let mut root = parsed_module("root");
        let mut root_usage =
            ExtensionUsage::new("@rules_owner//:extensions.bzl".to_owned(), "ext".to_owned());
        root_usage
            .repo_overrides
            .push(("generated".to_owned(), "actual_dep".to_owned()));
        root.extension_usages.push(root_usage);

        let mut owner = parsed_module("rules_owner");
        let mut owner_usage = ExtensionUsage::new("//:extensions.bzl".to_owned(), "ext".to_owned());
        owner_usage
            .imports
            .push(UseRepo::new().add_repo("generated".to_owned()));
        owner.extension_usages.push(owner_usage);

        let (cells, aliases) = pre_compute_extension_repo_cells(
            &[("root".to_owned(), root), ("rules_owner".to_owned(), owner)],
            "root",
            true,
            None,
        )
        .unwrap();

        assert_eq!(cells.len(), 1);
        assert_eq!(cells[0].canonical_name, "rules_owner++ext+generated");
        assert_eq!(aliases.len(), 1);
        assert_eq!(aliases[0].canonical_name, "rules_owner++ext+generated");
    }

    #[test]
    fn test_build_use_repo_aliases_positional() {
        let result = make_test_result();

        // use_repo(pip, "numpy", "requests")
        let use_repos = vec![
            UseRepo::new()
                .add_repo("numpy".to_owned())
                .add_repo("requests".to_owned()),
        ];

        let aliases = build_use_repo_aliases(&result, &use_repos).unwrap();

        // Should create aliases numpy -> rules_python++pip+numpy, etc.
        assert_eq!(aliases.len(), 2);

        let alias_map: HashMap<_, _> = aliases
            .iter()
            .map(|a| (a.apparent_name.as_str(), a.canonical_name.as_str()))
            .collect();

        assert_eq!(alias_map.get("numpy"), Some(&"rules_python++pip+numpy"));
        assert_eq!(
            alias_map.get("requests"),
            Some(&"rules_python++pip+requests")
        );
    }

    #[test]
    fn test_build_use_repo_aliases_keyword_mapping() {
        let result = make_test_result();

        // use_repo(pip, np = "numpy")
        let use_repos = vec![UseRepo::new().add_mapping("np".to_owned(), "numpy".to_owned())];

        let aliases = build_use_repo_aliases(&result, &use_repos).unwrap();

        assert_eq!(aliases.len(), 1);
        assert_eq!(aliases[0].apparent_name, "np");
        assert_eq!(aliases[0].canonical_name, "rules_python++pip+numpy");
    }

    #[test]
    fn test_build_use_repo_aliases_unknown_repo() {
        let result = make_test_result();

        // use_repo(pip, "pandas") - pandas not in result
        let use_repos = vec![UseRepo::new().add_repo("pandas".to_owned())];

        let aliases = build_use_repo_aliases(&result, &use_repos).unwrap();

        // Should not create alias for unknown repo
        assert_eq!(aliases.len(), 0);
    }

    #[test]
    fn test_build_extension_cell_definitions() {
        let result = make_test_result();
        let use_repos = vec![
            UseRepo::new()
                .add_repo("numpy".to_owned())
                .add_mapping("req".to_owned(), "requests".to_owned()),
        ];

        let defs = build_extension_cell_definitions(&result, &use_repos).unwrap();

        assert_eq!(defs.cell_count(), 2);
        // numpy (positional) + req (keyword mapping)
        assert_eq!(defs.alias_count(), 2);
    }

    #[test]
    fn test_is_extension_repo_canonical_name() {
        assert!(is_extension_repo_canonical_name("rules_python++pip+numpy"));
        assert!(is_extension_repo_canonical_name("_main+go_deps+gazelle"));
        assert!(is_extension_repo_canonical_name(
            "bazel_features++version_extension+bazel_features_version"
        ));
        assert!(!is_extension_repo_canonical_name("rules_cc"));
        assert!(!is_extension_repo_canonical_name("_main"));
    }

    #[test]
    fn test_parse_canonical_name() {
        assert_eq!(
            parse_canonical_name("rules_python++pip+numpy"),
            Some(("rules_python+", "pip", "numpy"))
        );
        assert_eq!(
            parse_canonical_name("_main+go_deps+com_github_foo_bar"),
            Some(("_main", "go_deps", "com_github_foo_bar"))
        );
        assert_eq!(
            parse_canonical_name("bazel_features++version_extension+bazel_features_version"),
            Some((
                "bazel_features+",
                "version_extension",
                "bazel_features_version"
            ))
        );
        assert_eq!(parse_canonical_name("rules_cc"), None);
        assert_eq!(parse_canonical_name("_main~pip"), None);
    }

    #[test]
    fn test_extension_cell_definitions_merge() {
        let result = make_test_result();
        let mut defs1 = build_extension_cells(&result).unwrap();

        let mut specs2 = fxhash::FxHashMap::default();
        specs2.insert(
            "gazelle".to_owned(),
            RepoSpec::new("@@rules_go//go:deps.bzl%go_deps".to_owned()),
        );
        let result2 = ModuleExtensionResult::new(
            Arc::from("@@rules_go//go:deps.bzl%go_deps"),
            "sha256-go".to_owned(),
            specs2,
            "",
        );
        let defs2 = build_extension_cells(&result2).unwrap();

        defs1.merge(defs2);
        assert_eq!(defs1.cell_count(), 3); // 2 + 1
    }

    #[test]
    fn test_extract_use_repos_for_extension() {
        let mut usage1 = ExtensionUsage::new("@rules_python//pip.bzl".to_owned(), "pip".to_owned());
        usage1
            .imports
            .push(UseRepo::new().add_repo("numpy".to_owned()));

        let mut usage2 = ExtensionUsage::new("@rules_go//go.bzl".to_owned(), "go_deps".to_owned());
        usage2
            .imports
            .push(UseRepo::new().add_repo("gazelle".to_owned()));

        let usages = vec![usage1, usage2];

        let pip_repos = extract_use_repos_for_extension("@rules_python//pip.bzl%pip", &usages);
        assert_eq!(pip_repos.len(), 1);
        assert_eq!(pip_repos[0].repos, vec!["numpy"]);

        let go_repos = extract_use_repos_for_extension("@rules_go//go.bzl%go_deps", &usages);
        assert_eq!(go_repos.len(), 1);
        assert_eq!(go_repos[0].repos, vec!["gazelle"]);
    }

    #[test]
    fn test_pending_repo_cell_fields() {
        let result = make_test_result();
        let defs = build_extension_cells(&result).unwrap();

        // Find numpy cell
        let numpy_cell = defs
            .cells
            .iter()
            .find(|c| c.internal_name == "numpy")
            .unwrap();
        assert_eq!(numpy_cell.canonical_name, "rules_python++pip+numpy");
        assert_eq!(numpy_cell.extension_id, "@@rules_python//pip:pip.bzl%pip");
        assert_eq!(numpy_cell.internal_name, "numpy");
        assert!(numpy_cell.spec_hash.starts_with("sha256-"));
        assert_eq!(numpy_cell.path, "bazel-external/rules_python++pip+numpy");

        // Verify repo_spec_json is valid JSON and can be deserialized
        let deserialized: RepoSpec = serde_json::from_str(&numpy_cell.repo_spec_json).unwrap();
        assert_eq!(
            deserialized.repo_rule_id,
            "@@rules_python//pip:pip.bzl%pip_install"
        );
        assert!(deserialized.attributes.contains_key("version"));
    }
}
