load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")
load("@slug_crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "slug_cli_v2",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/main.rs"],
    ),
    aliases = aliases(),
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    deps = all_crate_deps(normal = True) + [
        "//app/slug_commands_v2",
        "//app/slug_core_v2",
        "//app/slug_reapi_v2",
        "//app/slug_server_v2",
    ],
)

rust_test(
    name = "slug_cli_v2_test",
    crate = ":slug_cli_v2",
    size = "small",
    visibility = ["//visibility:private"],
)

rust_binary(
    name = "slug",
    crate_root = "src/main.rs",
    edition = crate_edition(),
    srcs = ["src/main.rs"],
    deps = [":slug_cli_v2"],
)

rust_test(
    name = "cli_fixture_test",
    srcs = [
        "tests/cli.rs",
        "//tests/v2_fixture_support:src/lib.rs",
    ],
    compile_data = ["//tests/v2_fixture_payload:fixtures.payload"],
    crate_root = "tests/cli.rs",
    data = [":slug"],
    edition = crate_edition(),
    size = "small",
    visibility = ["//visibility:private"],
    deps = [
        "//app/slug_commands_v2",
        "//app/slug_core_v2",
        "//app/slug_server_v2",
    ],
)

rust_test(
    name = "graph_output_fixture_test",
    srcs = [
        "tests/graph_output.rs",
        "//tests/v2_fixture_support:src/lib.rs",
    ],
    compile_data = ["//tests/v2_fixture_payload:fixtures.payload"],
    crate_root = "tests/graph_output.rs",
    data = [":slug"],
    edition = crate_edition(),
    size = "small",
    visibility = ["//visibility:private"],
)
