load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_library")
load("@slug_crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")

package(default_visibility = ["//visibility:public"])

cargo_build_script(
    name = "build_script",
    srcs = ["build.rs"],
    aliases = aliases(build = True, build_proc_macro = True),
    edition = crate_edition(),
    deps = all_crate_deps(build = True),
    proc_macro_deps = all_crate_deps(build_proc_macro = True),
)

rust_library(
    name = "starlark",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    edition = crate_edition(),
    deps = all_crate_deps(normal = True) + [
        ":build_script",
        "//allocative/allocative",
        "//gazebo/cmp_any",
        "//gazebo/display_container",
        "//gazebo/dupe",
        "//starlark-rust/starlark_map",
        "//starlark-rust/starlark_syntax",
    ],
    proc_macro_deps = all_crate_deps(proc_macro = True) + [
        "//starlark-rust/starlark_derive",
    ],
)
