load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("@slug_crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")

package(default_visibility = ["//visibility:public"])

_protos = [
    "proto/reapi_v2.proto",
    "proto/google/protobuf/any.proto",
    "proto/google/protobuf/duration.proto",
    "proto/google/rpc/status.proto",
    "proto/google/longrunning/operations.proto",
]

cargo_build_script(
    name = "build_script",
    srcs = ["build.rs"],
    aliases = aliases(build = True, build_proc_macro = True),
    build_script_env = {
        "SLUG_BAZEL_PROTOC": "$(execpath //:vendored_protoc)",
    },
    compile_data = _protos,
    crate_root = "build.rs",
    data = _protos + ["//:vendored_protoc_inputs"],
    edition = crate_edition(),
    deps = all_crate_deps(build = True),
    proc_macro_deps = all_crate_deps(build_proc_macro = True),
    tools = ["//:vendored_protoc"],
)

rust_library(
    name = "slug_reapi_v2",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    edition = crate_edition(),
    deps = all_crate_deps(normal = True) + [
        ":build_script",
        "//app/slug_build_api_v2",
        "//app/slug_core_v2",
    ],
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_test(
    name = "reapi_test",
    srcs = ["tests/reapi.rs"],
    edition = crate_edition(),
    size = "small",
    visibility = ["//visibility:private"],
    deps = [
        ":slug_reapi_v2",
        "//app/slug_build_api_v2",
        "@slug_crates//:prost",
        "@slug_crates//:tokio",
    ],
)
