[package]
description = "Slug V2 REAPI configuration and command substrate"
edition = "2024"
license = { workspace = true }
name = "slug_reapi_v2"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
sha2 = { workspace = true }
slug_build_api_v2 = { workspace = true }
slug_core_v2 = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["transport"] }

[build-dependencies]
protoc-bin-vendored = { workspace = true }
tonic-build = { workspace = true }
