load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("@slug_crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "slug_query_v2",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    edition = crate_edition(),
    deps = all_crate_deps(normal = True) + [
        "//allocative/allocative",
        "//app/slug_bzlmod_v2",
        "//app/slug_identity_v2",
        "//app/slug_loading_v2",
        "//app/slug_workspace_v2",
        "//dice/dice",
        "//gazebo/dupe",
        "//starlark-rust/starlark_map",
    ],
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_test(
    name = "slug_query_v2_test",
    crate = ":slug_query_v2",
    aliases = aliases(normal_dev = True),
    deps = all_crate_deps(normal_dev = True),
    size = "small",
    visibility = ["//visibility:private"],
)

rust_test(
    name = "query_test",
    srcs = ["tests/query.rs"],
    edition = crate_edition(),
    size = "small",
    visibility = ["//visibility:private"],
    deps = [":slug_query_v2"],
)
