[package]
description = "Slug V2 Bazel query expression substrate"
edition = "2024"
license = { workspace = true }
name = "slug_query_v2"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
async-trait = { workspace = true }
compact_str = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
futures = { workspace = true }
nom = { workspace = true }
slug_identity_v2 = { workspace = true }
slug_loading_v2 = { workspace = true }
starlark_map = { workspace = true }

[dev-dependencies]
slug_bzlmod_v2 = { workspace = true }
slug_workspace_v2 = { workspace = true }
tokio = { workspace = true }
