[package]
description = "Slug V2 Bazel analysis keys and configured target substrate"
edition = "2024"
license = { workspace = true }
name = "slug_analysis_v2"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
compact_str = { workspace = true }
dice = { workspace = true }
dice_futures = { workspace = true }
dupe = { workspace = true }
futures = { workspace = true }
num-bigint = { workspace = true }
slug_build_api_v2 = { workspace = true }
slug_bzlmod_v2 = { workspace = true }
slug_configuration_v2 = { workspace = true }
slug_events_v2 = { workspace = true }
slug_identity_v2 = { workspace = true }
slug_loading_v2 = { workspace = true }
slug_workspace_v2 = { workspace = true }
starlark = { workspace = true }
starlark_map = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
slug_bzlmod_v2 = { workspace = true }
