name: run_test_py
runs:
  using: composite
  steps:
  - name: Install Python test dependencies
    run: python3 -m pip install -r requirements-test.txt
    shell: bash
  - name: Run test.py
    run: python3 test.py --ci --git --slug=$RUNNER_TEMP/artifacts/slug
    shell: bash
