/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file.
 */

use std::hash::Hash;
use std::hash::Hasher;
use std::sync::Arc;

use allocative::Allocative;
use compact_str::CompactString;
use slug_identity_v2::ApparentRepoName;
use slug_identity_v2::CanonicalRepoName;
use slug_identity_v2::PackageIdentifier;

use crate::Depset;

/// The complete apparent-to-canonical repository view used by one package.
///
/// Repositories generated by the same extension or innate repository-rule
/// owner share a compact group. The group is an optimization identity for the
/// later manifest projection, not a repository name.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Allocative)]
pub struct RunfilesRepositoryMapping {
    entries: Arc<[(ApparentRepoName, CanonicalRepoName)]>,
    compact_group: Option<CompactString>,
}

impl RunfilesRepositoryMapping {
    pub fn new(
        entries: Arc<[(ApparentRepoName, CanonicalRepoName)]>,
        compact_group: Option<CompactString>,
    ) -> Self {
        Self {
            entries,
            compact_group,
        }
    }

    pub fn empty() -> Self {
        Self::new(Arc::from([]), None)
    }

    pub fn entries(&self) -> &[(ApparentRepoName, CanonicalRepoName)] {
        &self.entries
    }

    pub fn compact_group(&self) -> Option<&str> {
        self.compact_group.as_deref()
    }
}

/// Package identity and the exact selected repository view used to load it.
#[derive(Debug, Clone, PartialEq, Eq, Allocative)]
pub struct RunfilesPackageMetadata {
    package: PackageIdentifier,
    mapping: Arc<RunfilesRepositoryMapping>,
}

impl RunfilesPackageMetadata {
    pub fn new(package: PackageIdentifier, mapping: Arc<RunfilesRepositoryMapping>) -> Self {
        Self { package, mapping }
    }

    pub fn package(&self) -> &PackageIdentifier {
        &self.package
    }

    pub fn mapping(&self) -> &Arc<RunfilesRepositoryMapping> {
        &self.mapping
    }
}

// Bazel deliberately hashes package metadata by PackageIdentifier only. Full
// equality above resolves mapping collisions while preserving that cheap hash.
impl Hash for RunfilesPackageMetadata {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.package.hash(state);
    }
}

pub type RunfilesPackageDepset = Depset<Arc<RunfilesPackageMetadata>>;
