load(":defs.bzl", "probe_rule", "toolchain_impl")

constraint_setting(name = "owner_group")
constraint_value(name = "default_group", constraint_setting = ":owner_group")
constraint_value(name = "compile_group", constraint_setting = ":owner_group")

platform(
    name = "default_platform",
    constraint_values = [":default_group"],
    exec_properties = {"owner-group": "default", "stable": "default"},
)
platform(
    name = "compile_a",
    constraint_values = [":compile_group"],
    exec_properties = {"owner-group": "compile", "mutable": "A"},
)
platform(
    name = "compile_b",
    constraint_values = [":compile_group"],
    exec_properties = {"owner-group": "compile", "mutable": "B-platform"},
)

toolchain_type(name = "default_type")
toolchain_type(name = "compile_type")
toolchain_impl(name = "default_impl")
toolchain_impl(name = "compile_impl")
toolchain(
    name = "default_toolchain",
    exec_compatible_with = [":default_group"],
    toolchain = ":default_impl",
    toolchain_type = ":default_type",
)
toolchain(
    name = "compile_toolchain",
    exec_compatible_with = [":compile_group"],
    toolchain = ":compile_impl",
    toolchain_type = ":compile_type",
)
probe_rule(name = "probe")
