/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the above-listed
 * licenses.
 */

//! Cell registration for extension-generated repositories.
//!
//! This module provides infrastructure to register repositories created by module
//! extensions as "pending" cells that will be materialized lazily when first accessed.
//!
//! ## How It Works
//!
//! 1. Extension evaluation captures `RepoSpec` objects (no downloads)
//! 2. `ModuleExtensionResult` contains canonical names for each repo
//! 3. This module creates cell definitions for each repo
//! 4. When a repo is accessed, the cell resolver detects it's pending and triggers
//!    lazy execution via `ExtensionRepoExecutionKey`
//!
//! ## Naming Convention
//!
//! - **Canonical name**: `_main~{extension_name}~{internal_name}`
//!   - Example: `_main~pip~numpy`
//! - **Apparent name**: From `use_repo()` - maps to canonical
//!   - Example: `use_repo(pip, "numpy")` -> `@numpy` resolves to `@@_main~pip~numpy`
//!
//! ## Integration
//!
//! The cell definitions and aliases generated here are passed to `CellsAggregator`
//! in kuro_common during cell resolver construction.

use std::collections::HashMap;

use crate::extension_execution_dice::ModuleExtensionResult;
use crate::types::ExtensionUsage;
use crate::types::UseRepo;

/// A pending repository cell definition.
///
/// This represents a repository generated by a module extension that will
/// be materialized lazily when first accessed.
#[derive(Debug, Clone)]
pub struct PendingRepoCell {
    /// Canonical repository name (e.g., "_main~pip~numpy").
    pub canonical_name: String,
    /// Extension that generated this repo (e.g., "@@rules_python//pip:pip.bzl%pip").
    pub extension_id: String,
    /// Internal name within the extension (e.g., "numpy").
    pub internal_name: String,
    /// Hash of the RepoSpec for cache invalidation.
    pub spec_hash: String,
    /// JSON-serialized RepoSpec for lazy execution.
    pub repo_spec_json: String,
    /// Project-relative path where the repo will be materialized.
    pub path: String,
}

/// An alias from apparent name to canonical name.
#[derive(Debug, Clone)]
pub struct RepoAlias {
    /// The apparent name (e.g., "numpy" from `use_repo(pip, "numpy")`).
    pub apparent_name: String,
    /// The canonical name this resolves to (e.g., "_main~pip~numpy").
    pub canonical_name: String,
}

/// Cell definitions to register from extension execution.
///
/// Contains cells (with canonical names) and aliases (from use_repo).
#[derive(Debug, Clone, Default)]
pub struct ExtensionCellDefinitions {
    /// Pending repository cells.
    pub cells: Vec<PendingRepoCell>,
    /// Cell aliases: apparent name -> canonical name.
    pub aliases: Vec<RepoAlias>,
}

impl ExtensionCellDefinitions {
    /// Create empty definitions.
    pub fn new() -> Self {
        Self::default()
    }

    /// Check if there are any definitions.
    pub fn is_empty(&self) -> bool {
        self.cells.is_empty() && self.aliases.is_empty()
    }

    /// Number of cells defined.
    pub fn cell_count(&self) -> usize {
        self.cells.len()
    }

    /// Number of aliases defined.
    pub fn alias_count(&self) -> usize {
        self.aliases.len()
    }

    /// Merge with another set of definitions.
    pub fn merge(&mut self, other: ExtensionCellDefinitions) {
        self.cells.extend(other.cells);
        self.aliases.extend(other.aliases);
    }
}

/// Build cell definitions from a module extension result.
///
/// This creates:
/// 1. A cell for each generated repository with its canonical name
/// 2. A project-relative path at `bazel-external/{canonical_name}`
/// 3. Metadata for lazy materialization
/// 4. Serialized RepoSpec for lazy execution
///
/// # Arguments
/// * `result` - The module extension execution result
///
/// # Returns
/// Cell definitions ready to be passed to `CellsAggregator`.
pub fn build_extension_cells(result: &ModuleExtensionResult) -> kuro_error::Result<ExtensionCellDefinitions> {
    let mut defs = ExtensionCellDefinitions::new();

    for (internal_name, repo_spec) in &result.generated_repo_specs {
        let canonical = result
            .canonical_name(internal_name)
            .ok_or_else(|| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Input,
                    "Missing canonical name for repo '{}'",
                    internal_name
                )
            })?;

        // Path: bazel-external/{canonical_name}
        let path = format!("bazel-external/{}", canonical);

        // Serialize RepoSpec to JSON for lazy execution
        let repo_spec_json = serde_json::to_string(repo_spec).map_err(|e| {
            kuro_error::kuro_error!(
                kuro_error::ErrorTag::Input,
                "Failed to serialize RepoSpec for repo '{}': {}",
                internal_name,
                e
            )
        })?;

        let cell = PendingRepoCell {
            canonical_name: canonical.to_owned(),
            extension_id: result.extension_id.to_string(),
            internal_name: internal_name.clone(),
            spec_hash: repo_spec.compute_hash(),
            repo_spec_json,
            path,
        };

        defs.cells.push(cell);
    }

    Ok(defs)
}

/// Build cell aliases from use_repo() declarations.
///
/// This creates aliases so that apparent names from `use_repo()` resolve
/// to the canonical cell names.
///
/// # Example
/// `use_repo(pip, "numpy")` creates alias `numpy` -> `_main~pip~numpy`
/// `use_repo(pip, myname = "numpy")` creates alias `myname` -> `_main~pip~numpy`
///
/// # Arguments
/// * `extension_result` - The extension result with canonical name mappings
/// * `use_repos` - The use_repo() declarations from MODULE.bazel
///
/// # Returns
/// Aliases to add to the cell definitions.
pub fn build_use_repo_aliases(
    extension_result: &ModuleExtensionResult,
    use_repos: &[UseRepo],
) -> kuro_error::Result<Vec<RepoAlias>> {
    let mut aliases = Vec::new();

    for use_repo in use_repos {
        // Handle positional repo names: use_repo(ext, "repo1", "repo2")
        // These create aliases where apparent name == internal name
        for repo_name in &use_repo.repos {
            if let Some(canonical) = extension_result.canonical_name(repo_name) {
                // Don't create alias if apparent name equals canonical name
                if repo_name != canonical {
                    aliases.push(RepoAlias {
                        apparent_name: repo_name.clone(),
                        canonical_name: canonical.to_owned(),
                    });
                }
            } else {
                // Repo not found in extension result - may be an error or the repo
                // is from a different extension invocation
                tracing::debug!(
                    "use_repo references '{}' but it wasn't generated by extension '{}'",
                    repo_name,
                    extension_result.extension_id
                );
            }
        }

        // Handle keyword repo mappings: use_repo(ext, myname = "actual_repo")
        // apparent_name (myname) -> canonical_name of actual_repo
        for (apparent_name, actual_name) in &use_repo.repo_mapping {
            if let Some(canonical) = extension_result.canonical_name(actual_name) {
                aliases.push(RepoAlias {
                    apparent_name: apparent_name.clone(),
                    canonical_name: canonical.to_owned(),
                });
            } else {
                tracing::debug!(
                    "use_repo mapping '{}' -> '{}' not found in extension '{}'",
                    apparent_name,
                    actual_name,
                    extension_result.extension_id
                );
            }
        }
    }

    Ok(aliases)
}

/// Build complete cell definitions from extension result and use_repo declarations.
///
/// This is the main entry point that combines:
/// 1. Cell definitions for all generated repos
/// 2. Aliases from all use_repo() declarations
///
/// # Arguments
/// * `result` - The module extension execution result
/// * `use_repos` - All use_repo() declarations for this extension
///
/// # Returns
/// Complete cell definitions ready for `CellsAggregator`.
pub fn build_extension_cell_definitions(
    result: &ModuleExtensionResult,
    use_repos: &[UseRepo],
) -> kuro_error::Result<ExtensionCellDefinitions> {
    let mut defs = build_extension_cells(result)?;
    let aliases = build_use_repo_aliases(result, use_repos)?;
    defs.aliases.extend(aliases);
    Ok(defs)
}

/// Build cell definitions from multiple extension results.
///
/// This aggregates results from all extensions into a single set of
/// cell definitions.
///
/// # Arguments
/// * `extension_results` - Map from extension_id to (result, use_repos)
///
/// # Returns
/// Merged cell definitions for all extensions.
pub fn build_all_extension_cells(
    extension_results: &HashMap<String, (ModuleExtensionResult, Vec<UseRepo>)>,
) -> kuro_error::Result<ExtensionCellDefinitions> {
    let mut all_defs = ExtensionCellDefinitions::new();

    for (extension_id, (result, use_repos)) in extension_results {
        match build_extension_cell_definitions(result, use_repos) {
            Ok(defs) => {
                tracing::info!(
                    "Extension '{}' registered {} cells, {} aliases",
                    extension_id,
                    defs.cell_count(),
                    defs.alias_count()
                );
                all_defs.merge(defs);
            }
            Err(e) => {
                tracing::warn!(
                    "Failed to build cell definitions for extension '{}': {}",
                    extension_id,
                    e
                );
                return Err(e);
            }
        }
    }

    Ok(all_defs)
}

/// Extract use_repo declarations for a specific extension from extension usages.
///
/// This filters the use_repo declarations to only those for the given extension.
pub fn extract_use_repos_for_extension<'a>(
    extension_id: &str,
    extension_usages: &'a [ExtensionUsage],
) -> Vec<&'a UseRepo> {
    extension_usages
        .iter()
        .filter(|usage| usage.extension_id() == extension_id)
        .flat_map(|usage| usage.imports.iter())
        .collect()
}

/// Check if a cell name looks like an extension-generated canonical name.
///
/// Extension repos have canonical names like `_main~pip~numpy`.
pub fn is_extension_repo_canonical_name(name: &str) -> bool {
    // Pattern: _main~<extension>~<repo>
    // At least two ~ separators
    let parts: Vec<_> = name.split('~').collect();
    parts.len() >= 3 && parts[0].starts_with('_')
}

/// Parse an extension canonical name into components.
///
/// # Returns
/// `Some((prefix, extension_name, internal_name))` if valid, `None` otherwise.
///
/// # Example
/// `_main~pip~numpy` -> `Some(("_main", "pip", "numpy"))`
pub fn parse_canonical_name(canonical: &str) -> Option<(&str, &str, &str)> {
    let parts: Vec<_> = canonical.splitn(3, '~').collect();
    if parts.len() == 3 {
        Some((parts[0], parts[1], parts[2]))
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use crate::repo_spec::RepoSpec;
    use crate::repository_invocations::AttrValue;

    fn make_test_result() -> ModuleExtensionResult {
        let mut specs = HashMap::new();
        specs.insert(
            "numpy".to_owned(),
            RepoSpec::new("@@rules_python//pip:pip.bzl%pip_install".to_owned())
                .with_attr("version".to_owned(), AttrValue::String("1.24.0".to_owned())),
        );
        specs.insert(
            "requests".to_owned(),
            RepoSpec::new("@@rules_python//pip:pip.bzl%pip_install".to_owned())
                .with_attr("version".to_owned(), AttrValue::String("2.31.0".to_owned())),
        );

        ModuleExtensionResult::new(
            Arc::from("@@rules_python//pip:pip.bzl%pip"),
            "sha256-test".to_owned(),
            specs,
        )
    }

    #[test]
    fn test_build_extension_cells() {
        let result = make_test_result();
        let defs = build_extension_cells(&result).unwrap();

        assert_eq!(defs.cell_count(), 2);
        assert_eq!(defs.alias_count(), 0); // No aliases from this function

        // Check cell names are canonical
        let cell_names: Vec<_> = defs.cells.iter().map(|c| c.canonical_name.as_str()).collect();
        assert!(cell_names.contains(&"_main~pip~numpy"));
        assert!(cell_names.contains(&"_main~pip~requests"));

        // Check paths
        for cell in &defs.cells {
            assert!(cell.path.starts_with("bazel-external/_main~pip~"));
        }

        // Check extension IDs
        for cell in &defs.cells {
            assert_eq!(cell.extension_id, "@@rules_python//pip:pip.bzl%pip");
        }
    }

    #[test]
    fn test_build_use_repo_aliases_positional() {
        let result = make_test_result();

        // use_repo(pip, "numpy", "requests")
        let use_repos = vec![UseRepo::new()
            .add_repo("numpy".to_owned())
            .add_repo("requests".to_owned())];

        let aliases = build_use_repo_aliases(&result, &use_repos).unwrap();

        // Should create aliases numpy -> _main~pip~numpy, etc.
        assert_eq!(aliases.len(), 2);

        let alias_map: HashMap<_, _> = aliases
            .iter()
            .map(|a| (a.apparent_name.as_str(), a.canonical_name.as_str()))
            .collect();

        assert_eq!(alias_map.get("numpy"), Some(&"_main~pip~numpy"));
        assert_eq!(alias_map.get("requests"), Some(&"_main~pip~requests"));
    }

    #[test]
    fn test_build_use_repo_aliases_keyword_mapping() {
        let result = make_test_result();

        // use_repo(pip, np = "numpy")
        let use_repos = vec![UseRepo::new().add_mapping("np".to_owned(), "numpy".to_owned())];

        let aliases = build_use_repo_aliases(&result, &use_repos).unwrap();

        assert_eq!(aliases.len(), 1);
        assert_eq!(aliases[0].apparent_name, "np");
        assert_eq!(aliases[0].canonical_name, "_main~pip~numpy");
    }

    #[test]
    fn test_build_use_repo_aliases_unknown_repo() {
        let result = make_test_result();

        // use_repo(pip, "pandas") - pandas not in result
        let use_repos = vec![UseRepo::new().add_repo("pandas".to_owned())];

        let aliases = build_use_repo_aliases(&result, &use_repos).unwrap();

        // Should not create alias for unknown repo
        assert_eq!(aliases.len(), 0);
    }

    #[test]
    fn test_build_extension_cell_definitions() {
        let result = make_test_result();
        let use_repos = vec![UseRepo::new()
            .add_repo("numpy".to_owned())
            .add_mapping("req".to_owned(), "requests".to_owned())];

        let defs = build_extension_cell_definitions(&result, &use_repos).unwrap();

        assert_eq!(defs.cell_count(), 2);
        // numpy (positional) + req (keyword mapping)
        assert_eq!(defs.alias_count(), 2);
    }

    #[test]
    fn test_is_extension_repo_canonical_name() {
        assert!(is_extension_repo_canonical_name("_main~pip~numpy"));
        assert!(is_extension_repo_canonical_name("_main~go_deps~gazelle"));
        assert!(!is_extension_repo_canonical_name("rules_cc"));
        assert!(!is_extension_repo_canonical_name("_main"));
        assert!(!is_extension_repo_canonical_name("_main~pip"));
    }

    #[test]
    fn test_parse_canonical_name() {
        assert_eq!(
            parse_canonical_name("_main~pip~numpy"),
            Some(("_main", "pip", "numpy"))
        );
        assert_eq!(
            parse_canonical_name("_main~go_deps~com_github_foo_bar"),
            Some(("_main", "go_deps", "com_github_foo_bar"))
        );
        assert_eq!(parse_canonical_name("rules_cc"), None);
        assert_eq!(parse_canonical_name("_main~pip"), None);
    }

    #[test]
    fn test_extension_cell_definitions_merge() {
        let result = make_test_result();
        let mut defs1 = build_extension_cells(&result).unwrap();

        let mut specs2 = HashMap::new();
        specs2.insert(
            "gazelle".to_owned(),
            RepoSpec::new("@@rules_go//go:deps.bzl%go_deps".to_owned()),
        );
        let result2 = ModuleExtensionResult::new(
            Arc::from("@@rules_go//go:deps.bzl%go_deps"),
            "sha256-go".to_owned(),
            specs2,
        );
        let defs2 = build_extension_cells(&result2).unwrap();

        defs1.merge(defs2);
        assert_eq!(defs1.cell_count(), 3); // 2 + 1
    }

    #[test]
    fn test_extract_use_repos_for_extension() {
        let mut usage1 = ExtensionUsage::new(
            "@rules_python//pip.bzl".to_owned(),
            "pip".to_owned(),
        );
        usage1.imports.push(UseRepo::new().add_repo("numpy".to_owned()));

        let mut usage2 = ExtensionUsage::new(
            "@rules_go//go.bzl".to_owned(),
            "go_deps".to_owned(),
        );
        usage2.imports.push(UseRepo::new().add_repo("gazelle".to_owned()));

        let usages = vec![usage1, usage2];

        let pip_repos = extract_use_repos_for_extension("@rules_python//pip.bzl%pip", &usages);
        assert_eq!(pip_repos.len(), 1);
        assert_eq!(pip_repos[0].repos, vec!["numpy"]);

        let go_repos = extract_use_repos_for_extension("@rules_go//go.bzl%go_deps", &usages);
        assert_eq!(go_repos.len(), 1);
        assert_eq!(go_repos[0].repos, vec!["gazelle"]);
    }

    #[test]
    fn test_pending_repo_cell_fields() {
        let result = make_test_result();
        let defs = build_extension_cells(&result).unwrap();

        // Find numpy cell
        let numpy_cell = defs.cells.iter().find(|c| c.internal_name == "numpy").unwrap();
        assert_eq!(numpy_cell.canonical_name, "_main~pip~numpy");
        assert_eq!(numpy_cell.extension_id, "@@rules_python//pip:pip.bzl%pip");
        assert_eq!(numpy_cell.internal_name, "numpy");
        assert!(numpy_cell.spec_hash.starts_with("sha256-"));
        assert_eq!(numpy_cell.path, "bazel-external/_main~pip~numpy");

        // Verify repo_spec_json is valid JSON and can be deserialized
        let deserialized: RepoSpec = serde_json::from_str(&numpy_cell.repo_spec_json).unwrap();
        assert_eq!(deserialized.repo_rule_id, "@@rules_python//pip:pip.bzl%pip_install");
        assert!(deserialized.attributes.contains_key("version"));
    }
}
