/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

//! Extension repository external cell implementation.
//!
//! Extension-generated repositories are created by module extensions (e.g., pip.parse(),
//! go_deps, maven.install()). They use a deferred execution model:
//!
//! 1. During extension evaluation, `RepoSpec` objects are captured (no downloads)
//! 2. When a repo is first accessed, the `RepoSpec` is executed to materialize it
//! 3. Materialized repos are stored at `bazel-external/{canonical_name}`
//!
//! This module provides file operations for extension repos. When a repo isn't
//! materialized yet, lazy materialization is triggered via `ExtensionRepoExecutionKey`.

use std::fmt::Display;
use std::path::PathBuf;
use std::sync::Arc;

use async_trait::async_trait;
use cmp_any::PartialEqAny;
use compact_str::CompactString;
use dice::DiceComputations;
use slug_bzlmod::ExtensionRepoExecutionKey;
use slug_bzlmod::RepoSpec;
use slug_common::dice::cells::HasCellResolver;
use slug_common::dice::data::HasIoProvider;
use slug_common::external_symlink::ExternalSymlink;
use slug_common::file_ops::delegate::FileOpsDelegate;
use slug_common::file_ops::dice::ReadFileProxy;
use slug_common::file_ops::metadata::FileMetadata;
use slug_common::file_ops::metadata::FileType;
use slug_common::file_ops::metadata::RawDirEntry;
use slug_common::file_ops::metadata::RawPathMetadata;
use slug_common::file_ops::metadata::RawSymlink;
use slug_common::file_ops::metadata::TrackedFileDigest;
use slug_core::cells::cell_path::CellPath;
use slug_core::cells::external::ExtensionRepoCellSetup;
use slug_core::cells::name::CellName;
use slug_core::cells::paths::CellRelativePath;
use slug_core::cells::paths::CellRelativePathBuf;
use slug_execute::digest_config::DigestConfig;
use slug_execute::digest_config::HasDigestConfig;
use slug_fs::paths::forward_rel_path::ForwardRelativePathBuf;

/// Error for extension repos.
#[derive(Debug, slug_error::Error)]
#[slug(tag = Input)]
pub enum ExtensionRepoError {
    #[error(
        "Extension repository '{}' has not been materialized yet. \
         This repo is generated by extension '{}' and needs to be lazily executed.",
        canonical_name,
        extension_id
    )]
    NotMaterialized {
        canonical_name: String,
        extension_id: String,
    },

    #[error(
        "Failed to deserialize RepoSpec for extension repository '{}': {}",
        canonical_name,
        reason
    )]
    DeserializationFailed {
        canonical_name: String,
        reason: String,
    },

    #[error(
        "Failed to materialize extension repository '{}': {}",
        canonical_name,
        reason
    )]
    MaterializationFailed {
        canonical_name: String,
        reason: String,
    },
}

fn diagnostic_summary(error: impl Display) -> String {
    const MAX_CHARS: usize = 2000;
    let rendered = format!("{error:#}");
    let mut iter = rendered.char_indices();
    let Some((idx, _)) = iter.nth(MAX_CHARS) else {
        return rendered;
    };
    let omitted = rendered[idx..].chars().count();
    format!(
        "{} ... (truncated; {} chars omitted)",
        &rendered[..idx],
        omitted
    )
}

fn repo_names_summary<'a>(repo_names: impl Iterator<Item = &'a str>) -> String {
    const MAX_REPOS: usize = 25;
    let mut names = Vec::new();
    let mut total = 0usize;
    for name in repo_names {
        total += 1;
        if names.len() < MAX_REPOS {
            names.push(name.to_owned());
        }
    }
    if total <= MAX_REPOS {
        format!("{:?}", names)
    } else {
        format!(
            "{:?} (showing {} of {}; {} omitted)",
            names,
            names.len(),
            total,
            total - names.len()
        )
    }
}

#[cfg(test)]
fn complete_marker(spec_hash: &str, output_digest: Option<&str>) -> String {
    match (spec_hash.is_empty(), output_digest) {
        (true, None) => "complete".to_owned(),
        (true, Some(output_digest)) => format!("complete:output:{output_digest}"),
        (false, Some(output_digest)) => format!("complete:{spec_hash}:output:{output_digest}"),
        (false, None) => format!("complete:{spec_hash}"),
    }
}

#[cfg(test)]
fn is_complete_marker(marker: &str) -> bool {
    let marker = marker.trim();
    marker == "complete" || marker.starts_with("complete:")
}

#[cfg(test)]
fn is_output_state_marker(marker: &str) -> bool {
    marker.trim().contains(":output:")
}

#[cfg(test)]
fn complete_marker_expected_output<'a>(marker: &'a str, spec_hash: &str) -> Option<&'a str> {
    let marker = marker.trim();
    if spec_hash.is_empty() {
        return marker.strip_prefix("complete:output:");
    }
    marker.strip_prefix(&format!("complete:{spec_hash}:output:"))
}

#[cfg(test)]
fn complete_marker_matches(marker: &str, spec_hash: &str) -> bool {
    let marker = marker.trim();
    if spec_hash.is_empty() {
        return marker == "complete" || marker.starts_with("complete:output:");
    }
    marker
        .strip_prefix(&format!("complete:{spec_hash}:output:"))
        .is_some_and(|output_digest| !output_digest.is_empty())
}

#[cfg(test)]
fn complete_marker_output_state_is_stale(
    repo_path: &std::path::Path,
    marker: &str,
    spec_hash: &str,
) -> bool {
    let Some(expected_output_digest) = complete_marker_expected_output(marker, spec_hash) else {
        return false;
    };
    slug_bzlmod::repository_output_digest(repo_path)
        .map(|current_output_digest| current_output_digest != expected_output_digest)
        .unwrap_or(true)
}

/// File operations delegate for extension-generated repositories.
///
/// This delegate reads files from the materialized repository path
/// (typically `bazel-external/{canonical_name}`).
#[derive(allocative::Allocative)]
pub(crate) struct ExtensionRepoFileOpsDelegate {
    /// The cell name.
    cell_name: CellName,
    /// The canonical name of the repository (e.g., "_main+pip+numpy").
    /// Kept for debugging and error messages.
    #[allow(dead_code)]
    canonical_name: String,
    /// The absolute path to the materialized repository content.
    source_path: PathBuf,
    /// Digest config for computing file digests.
    digest_config: DigestConfig,
}

impl ExtensionRepoFileOpsDelegate {
    pub fn new(
        cell_name: CellName,
        canonical_name: String,
        source_path: PathBuf,
        digest_config: DigestConfig,
    ) -> Self {
        Self {
            cell_name,
            canonical_name,
            source_path,
            digest_config,
        }
    }

    fn resolve_path(&self, path: &CellRelativePath) -> PathBuf {
        self.source_path.join(path.as_str())
    }

    fn make_cell_path(&self, path: &CellRelativePath) -> Arc<CellPath> {
        Arc::new(CellPath::new(
            self.cell_name,
            CellRelativePathBuf::from(path.to_owned()),
        ))
    }
}

#[async_trait]
impl FileOpsDelegate for ExtensionRepoFileOpsDelegate {
    async fn read_file_if_exists(
        &self,
        _ctx: &mut DiceComputations<'_>,
        path: &'async_trait CellRelativePath,
    ) -> slug_error::Result<ReadFileProxy> {
        let abs_path = self.resolve_path(path);
        Ok(ReadFileProxy::new_with_captures(
            abs_path,
            |abs_path| async move {
                match tokio::fs::read_to_string(&abs_path).await {
                    Ok(contents) => Ok(Some(contents)),
                    Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
                    Err(e) => Err(slug_error::slug_error!(
                        slug_error::ErrorTag::Environment,
                        "Failed to read extension repo file {:?}: {}",
                        abs_path,
                        e
                    )),
                }
            },
        ))
    }

    async fn read_dir(
        &self,
        _ctx: &mut DiceComputations<'_>,
        path: &'async_trait CellRelativePath,
    ) -> slug_error::Result<Arc<[RawDirEntry]>> {
        let abs_path = self.resolve_path(path);

        let mut entries = Vec::new();
        let mut read_dir = tokio::fs::read_dir(&abs_path).await.map_err(|e| {
            slug_error::slug_error!(
                slug_error::ErrorTag::Environment,
                "Failed to read extension repo directory {:?}: {}",
                abs_path,
                e
            )
        })?;

        while let Some(entry) = read_dir.next_entry().await.map_err(|e| {
            slug_error::slug_error!(
                slug_error::ErrorTag::Environment,
                "Failed to read directory entry: {}",
                e
            )
        })? {
            // Follow symlinks when classifying the entry type. Repository rules like
            // rules_cc's llvm_configure use `repository_ctx.symlink` to materialize
            // entire source subtrees as directory symlinks (e.g., llvm/lib -> ...);
            // `DirEntry::file_type` does not follow symlinks, so those entries would
            // come back as `FileType::Symlink`. gather_package_listing only recurses
            // into `FileType::Directory`, so classifying symlinks-to-dirs as
            // directories is required for `glob()` to see files inside.
            let file_name_os = entry.file_name();
            let file_name = file_name_os.into_string().map_err(|_| {
                slug_error::slug_error!(
                    slug_error::ErrorTag::Environment,
                    "Non-UTF8 filename in {:?}",
                    abs_path
                )
            })?;

            let entry_path = entry.path();
            let resolved = tokio::fs::metadata(&entry_path).await;
            let file_type = match resolved {
                Ok(md) if md.is_dir() => FileType::Directory,
                Ok(_) => FileType::File,
                Err(_) => {
                    // Broken or inaccessible symlink — fall back to the symlink's
                    // own metadata so we at least report the entry instead of
                    // failing the entire directory read.
                    let st = entry.file_type().await.map_err(|e| {
                        slug_error::slug_error!(
                            slug_error::ErrorTag::Environment,
                            "Failed to get file type: {}",
                            e
                        )
                    })?;
                    if st.is_dir() {
                        FileType::Directory
                    } else if st.is_symlink() {
                        FileType::Symlink
                    } else {
                        FileType::File
                    }
                }
            };

            entries.push(RawDirEntry {
                file_name: CompactString::from(file_name),
                file_type,
            });
        }

        // Sort entries for deterministic output
        entries.sort_by(|a, b| a.file_name.cmp(&b.file_name));

        Ok(entries.into())
    }

    async fn read_path_metadata_if_exists(
        &self,
        _ctx: &mut DiceComputations<'_>,
        path: &'async_trait CellRelativePath,
    ) -> slug_error::Result<Option<RawPathMetadata>> {
        let abs_path = self.resolve_path(path);

        let metadata = match tokio::fs::symlink_metadata(&abs_path).await {
            Ok(m) => m,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(e) => {
                return Err(slug_error::slug_error!(
                    slug_error::ErrorTag::Environment,
                    "Failed to get metadata for extension repo file {:?}: {}",
                    abs_path,
                    e
                ));
            }
        };

        if metadata.is_dir() {
            Ok(Some(RawPathMetadata::Directory))
        } else if metadata.is_symlink() {
            // Read symlink target
            let target = tokio::fs::read_link(&abs_path).await.map_err(|e| {
                slug_error::slug_error!(
                    slug_error::ErrorTag::Environment,
                    "Failed to read symlink {:?}: {}",
                    abs_path,
                    e
                )
            })?;

            let cell_path = self.make_cell_path(path);

            // Treat symlinks as external
            let external = ExternalSymlink::new(target, ForwardRelativePathBuf::empty())?;
            Ok(Some(RawPathMetadata::Symlink {
                at: cell_path,
                to: RawSymlink::External(Arc::new(external)),
            }))
        } else {
            // Regular file
            let contents = tokio::fs::read(&abs_path).await.map_err(|e| {
                slug_error::slug_error!(
                    slug_error::ErrorTag::Environment,
                    "Failed to read extension repo file {:?}: {}",
                    abs_path,
                    e
                )
            })?;

            let source_config = self.digest_config.cas_digest_config().source_files_config();
            let digest = TrackedFileDigest::from_content(&contents, source_config);

            #[cfg(unix)]
            let is_executable = {
                use std::os::unix::fs::PermissionsExt;
                metadata.permissions().mode() & 0o111 != 0
            };
            #[cfg(not(unix))]
            let is_executable = false;

            Ok(Some(RawPathMetadata::File(FileMetadata {
                digest,
                is_executable,
            })))
        }
    }

    fn eq_token(&self) -> PartialEqAny<'_> {
        PartialEqAny::always_false()
    }
}

/// Idempotently register every sibling spoke of `extension_id` on the current
/// resolver. Returns silently if this is not a module extension (e.g. a
/// `use_repo_rule()` invocation, which has no siblings).
async fn ensure_extension_spokes_registered(
    ctx: &mut DiceComputations<'_>,
    workspace_id: &slug_bzlmod::WorkspaceId,
    extension_id: &str,
    requesting_canonical_name: &str,
) -> slug_error::Result<Option<Arc<slug_bzlmod::ExtensionSpokesValue>>> {
    let lookup_key = slug_bzlmod::ExtensionSpokesByExtensionIdKey::for_workspace_id(
        workspace_id.clone(),
        extension_id,
    );
    let Some(spokes) = (match ctx.compute(&lookup_key).await {
        Ok(Ok(spokes)) => spokes,
        Ok(Err(e)) => {
            return Err(ExtensionRepoError::MaterializationFailed {
                canonical_name: requesting_canonical_name.to_owned(),
                reason: format!(
                    "Extension '{}' spoke lookup failed while registering spokes: {}",
                    extension_id,
                    diagnostic_summary(&e)
                ),
            }
            .into());
        }
        Err(e) => {
            return Err(ExtensionRepoError::MaterializationFailed {
                canonical_name: requesting_canonical_name.to_owned(),
                reason: format!(
                    "Extension '{}' DICE error while looking up spokes: {}",
                    extension_id,
                    diagnostic_summary(&e)
                ),
            }
            .into());
        }
    }) else {
        // Not a module extension — `use_repo_rule()` and similar produce a
        // single repo with no siblings, so there is nothing to seed.
        return Ok(None);
    };

    let cell_resolver = ctx.get_cell_resolver().await?;
    for spoke in spokes.iter() {
        let cell_setup =
            extension_repo_cell_setup_from_spoke(extension_id, spoke, &spokes.repo_env);
        let path = format!("bazel-external/{}", spoke.canonical_name);
        cell_resolver.register_bzlmod_runtime_extension_cell(
            spoke.canonical_name.as_ref(),
            &path,
            cell_setup.clone(),
        )?;
        if spoke.internal_name != spoke.canonical_name {
            cell_resolver.register_bzlmod_runtime_extension_cell(
                spoke.internal_name.as_ref(),
                &path,
                cell_setup,
            )?;
        }
    }

    Ok(Some(spokes))
}

async fn workspace_id_for_extension_spoke_lookup(
    ctx: &mut DiceComputations<'_>,
    requesting_canonical_name: &str,
) -> slug_error::Result<slug_bzlmod::WorkspaceId> {
    ctx.compute(&slug_bzlmod::BzlmodCellGraphDataKey)
        .await
        .map(|data| data.workspace_id.clone())
        .map_err(|e| {
            ExtensionRepoError::MaterializationFailed {
                canonical_name: requesting_canonical_name.to_owned(),
                reason: format!(
                    "DICE error while reading bzlmod workspace identity: {}",
                    diagnostic_summary(&e)
                ),
            }
            .into()
        })
}

fn extension_repo_cell_setup_from_spoke(
    extension_id: &str,
    spoke: &slug_bzlmod::ExtensionSpoke,
    repo_env: &std::collections::BTreeMap<String, String>,
) -> ExtensionRepoCellSetup {
    ExtensionRepoCellSetup {
        canonical_name: spoke.canonical_name.clone(),
        extension_id: std::sync::Arc::from(extension_id),
        internal_name: spoke.internal_name.clone(),
        spec_hash: spoke.spec_hash.clone(),
        repo_spec_json: spoke.repo_spec_json.clone(),
        repo_env_json: std::sync::Arc::from(
            serde_json::to_string(repo_env)
                .unwrap_or_else(|_| "{}".to_owned())
                .as_str(),
        ),
        materialized: false,
    }
}

fn repo_env_from_setup(
    setup: &ExtensionRepoCellSetup,
) -> slug_error::Result<Arc<std::collections::BTreeMap<String, String>>> {
    if setup.repo_env_json.is_empty() {
        return Ok(Arc::new(std::collections::BTreeMap::new()));
    }
    serde_json::from_str::<std::collections::BTreeMap<String, String>>(&setup.repo_env_json)
        .map(Arc::new)
        .map_err(|e| {
            slug_error::slug_error!(
                slug_error::ErrorTag::Input,
                "Failed to parse repo_env for extension repo '{}': {}",
                setup.canonical_name,
                e
            )
        })
}

/// Get the file ops delegate for an extension-generated repository cell.
///
/// This computes the expected path for the materialized repository
/// (`bazel-external/{canonical_name}`) and triggers lazy materialization
/// if the repository hasn't been materialized yet.
///
/// ## Lazy Materialization Flow
///
/// 1. Check if the repository is already materialized (exists on disk)
/// 2. If not materialized, deserialize the `RepoSpec` from `repo_spec_json`
/// 3. Create and compute `ExtensionRepoExecutionKey` via DICE
/// 4. This executes the repository rule (e.g., http_archive) and materializes the repo
/// 5. Return a file ops delegate pointing to the materialized content
pub(crate) async fn get_file_ops_delegate(
    ctx: &mut DiceComputations<'_>,
    cell_name: CellName,
    setup: ExtensionRepoCellSetup,
) -> slug_error::Result<Arc<dyn FileOpsDelegate>> {
    let digest_config = ctx.global_data().get_digest_config();

    // Compute the expected path for the materialized repository
    let io = ctx.global_data().get_io_provider();
    let project_root = io.project_root();
    let project_root_path = project_root.root().to_path_buf();
    let source_path = project_root_path
        .join("bazel-external")
        .join(setup.canonical_name.as_ref());

    // Make sure every sibling spoke of this extension is registered on the
    // current resolver. Necessary on warm builds where `.slug_repo_complete`
    // markers would otherwise skip the materialization block below, leaving
    // spoke lookups unresolvable.
    let extension_lookup_workspace_id =
        workspace_id_for_extension_spoke_lookup(ctx, setup.canonical_name.as_ref()).await?;
    let registered_spokes = ensure_extension_spokes_registered(
        ctx,
        &extension_lookup_workspace_id,
        &setup.extension_id,
        setup.canonical_name.as_ref(),
    )
    .await?;
    // A dynamic cell origin can outlive the command that created it. Prefer
    // the current DICE spoke value when this is a module-extension repo.
    let repo_env = match registered_spokes.as_ref() {
        Some(spokes) => spokes.repo_env.clone(),
        None if !setup.repo_env_json.is_empty() => repo_env_from_setup(&setup)?,
        None => Arc::new(std::collections::BTreeMap::new()),
    };

    let repo_spec_for_execution = if let Some(spokes) = registered_spokes.as_ref() {
        match spokes
            .by_internal_name(setup.internal_name.as_ref())
            .or_else(|| spokes.by_canonical_name(setup.canonical_name.as_ref()))
        {
            Some(spoke) => Some(spoke.repo_spec.as_ref().clone()),
            None => {
                return Err(ExtensionRepoError::MaterializationFailed {
                    canonical_name: setup.canonical_name.to_string(),
                    reason: format!(
                        "Extension '{}' did not generate repo '{}' (available: {})",
                        setup.extension_id,
                        setup.internal_name,
                        repo_names_summary(spokes.spokes.keys().map(|name| name.as_str()))
                    ),
                }
                .into());
            }
        }
    } else if !setup.repo_spec_json.is_empty() {
        Some(
            serde_json::from_str::<RepoSpec>(&setup.repo_spec_json).map_err(|e| {
                ExtensionRepoError::DeserializationFailed {
                    canonical_name: setup.canonical_name.to_string(),
                    reason: e.to_string(),
                }
            })?,
        )
    } else {
        None
    };
    if let Some(repo_spec) = repo_spec_for_execution {
        let key = ExtensionRepoExecutionKey::new_with_workspace_id_and_repo_env(
            setup.canonical_name.to_string(),
            setup.extension_id.to_string(),
            repo_spec,
            extension_lookup_workspace_id.clone(),
            repo_env.clone(),
        );
        match ctx.compute(&key).await {
            Ok(Ok(repo_result)) => {
                tracing::debug!(
                    "Validated extension repo '{}' at {:?}",
                    setup.canonical_name,
                    repo_result.repo_path
                );
            }
            Ok(Err(e)) => {
                return Err(ExtensionRepoError::MaterializationFailed {
                    canonical_name: setup.canonical_name.to_string(),
                    reason: format!("Repo rule execution failed: {}", diagnostic_summary(&e)),
                }
                .into());
            }
            Err(e) => {
                return Err(ExtensionRepoError::MaterializationFailed {
                    canonical_name: setup.canonical_name.to_string(),
                    reason: format!(
                        "DICE computation failed during repo rule execution: {}",
                        diagnostic_summary(&e)
                    ),
                }
                .into());
            }
        }
        if !source_path.exists() {
            return Err(ExtensionRepoError::MaterializationFailed {
                canonical_name: setup.canonical_name.to_string(),
                reason: "Repository not found after repo rule execution".to_owned(),
            }
            .into());
        }
        return Ok(Arc::new(ExtensionRepoFileOpsDelegate::new(
            cell_name,
            setup.canonical_name.to_string(),
            source_path,
            digest_config,
        )));
    }
    tracing::info!(
        "No current RepoSpec for '{}', resolving extension '{}' via DICE",
        setup.canonical_name,
        setup.extension_id
    );

    // No current RepoSpec was available from setup or registered extension
    // spokes. Do not trust an existing completion marker here; look up the
    // DICE-owned spoke or enter the repository execution key so its
    // materialization manifest owns reuse.
    let repo_spec = {
        let lookup_key = slug_bzlmod::ExtensionSpokesByExtensionIdKey::for_workspace_id(
            extension_lookup_workspace_id.clone(),
            &setup.extension_id,
        );
        let spokes = match ctx.compute(&lookup_key).await {
            Ok(Ok(Some(result))) => result,
            Ok(Ok(None)) => {
                // Not a module extension — likely a use_repo_rule() invocation.
                // Execute directly as a Starlark repository rule via DICE.
                tracing::info!(
                    "Extension '{}' not in aggregations, treating as use_repo_rule for '{}'",
                    setup.extension_id,
                    setup.canonical_name
                );
                let mut inv = slug_bzlmod::RepositoryInvocation::new(
                    setup.canonical_name.to_string(),
                    setup
                        .extension_id
                        .split('%')
                        .last()
                        .unwrap_or("unknown")
                        .to_owned(),
                );
                inv.rule_source = Some(setup.extension_id.to_string());
                let repo_spec = slug_bzlmod::RepoSpec::new(setup.extension_id.to_string());
                let key = ExtensionRepoExecutionKey::new_with_workspace_id_and_repo_env(
                    setup.canonical_name.to_string(),
                    setup.extension_id.to_string(),
                    repo_spec,
                    extension_lookup_workspace_id.clone(),
                    repo_env.clone(),
                );
                match ctx.compute(&key).await {
                    Ok(Ok(repo_result)) => {
                        tracing::info!(
                            "Materialized use_repo_rule repo '{}' at {:?}",
                            setup.canonical_name,
                            repo_result.repo_path
                        );
                    }
                    Ok(Err(e)) => {
                        return Err(ExtensionRepoError::MaterializationFailed {
                            canonical_name: setup.canonical_name.to_string(),
                            reason: format!(
                                "use_repo_rule execution failed: {}",
                                diagnostic_summary(&e)
                            ),
                        }
                        .into());
                    }
                    Err(e) => {
                        return Err(ExtensionRepoError::MaterializationFailed {
                            canonical_name: setup.canonical_name.to_string(),
                            reason: format!(
                                "DICE error during use_repo_rule execution: {}",
                                diagnostic_summary(&e)
                            ),
                        }
                        .into());
                    }
                }
                // Skip the extension execution path below
                if !source_path.exists() {
                    return Err(ExtensionRepoError::MaterializationFailed {
                        canonical_name: setup.canonical_name.to_string(),
                        reason: "Repository not found after use_repo_rule execution".to_owned(),
                    }
                    .into());
                }
                // declare_all_source_artifacts_ext skipped: lazy file tracking via ExtensionRepoFileOpsDelegate
                return Ok(Arc::new(ExtensionRepoFileOpsDelegate::new(
                    cell_name,
                    setup.canonical_name.to_string(),
                    source_path,
                    digest_config,
                )));
            }
            Ok(Err(e)) => {
                return Err(ExtensionRepoError::MaterializationFailed {
                    canonical_name: setup.canonical_name.to_string(),
                    reason: format!(
                        "Extension '{}' spoke lookup failed: {}",
                        setup.extension_id,
                        diagnostic_summary(&e)
                    ),
                }
                .into());
            }
            Err(e) => {
                return Err(ExtensionRepoError::MaterializationFailed {
                    canonical_name: setup.canonical_name.to_string(),
                    reason: format!(
                        "Extension '{}' DICE error while looking up spokes: {}",
                        setup.extension_id,
                        diagnostic_summary(&e)
                    ),
                }
                .into());
            }
        };

        // Spoke registration moved to `ensure_extension_spokes_registered`
        // at the top of `get_file_ops_delegate` so it runs even when the
        // hub already has `.slug_repo_complete`. This block now resolves
        // the current repo's spec out of the DICE-owned spoke value.

        match spokes
            .by_internal_name(&setup.internal_name)
            .or_else(|| spokes.by_canonical_name(&setup.canonical_name))
        {
            Some(spoke) => spoke.repo_spec.as_ref().clone(),
            None => {
                return Err(ExtensionRepoError::MaterializationFailed {
                    canonical_name: setup.canonical_name.to_string(),
                    reason: format!(
                        "Extension '{}' did not generate repo '{}' (available: {})",
                        setup.extension_id,
                        setup.internal_name,
                        repo_names_summary(spokes.spokes.keys().map(|name| name.as_str()))
                    ),
                }
                .into());
            }
        }
    };

    // Create the execution key for lazy materialization of this specific repo
    let key = ExtensionRepoExecutionKey::new_with_workspace_id_and_repo_env(
        setup.canonical_name.to_string(),
        setup.extension_id.to_string(),
        repo_spec,
        extension_lookup_workspace_id.clone(),
        repo_env.clone(),
    );

    // Execute via DICE to materialize the repository
    match ctx.compute(&key).await {
        Ok(Ok(repo_result)) => {
            tracing::info!(
                "Successfully materialized extension repo '{}' at {:?}",
                setup.canonical_name,
                repo_result.repo_path
            );
        }
        Ok(Err(e)) => {
            return Err(ExtensionRepoError::MaterializationFailed {
                canonical_name: setup.canonical_name.to_string(),
                reason: format!("Repo rule execution failed: {}", diagnostic_summary(&e)),
            }
            .into());
        }
        Err(e) => {
            return Err(ExtensionRepoError::MaterializationFailed {
                canonical_name: setup.canonical_name.to_string(),
                reason: format!(
                    "DICE computation failed during repo rule execution: {}",
                    diagnostic_summary(&e)
                ),
            }
            .into());
        }
    }

    // At this point, the repository should exist on disk
    if !source_path.exists() {
        return Err(ExtensionRepoError::MaterializationFailed {
            canonical_name: setup.canonical_name.to_string(),
            reason: "Repository not found after materialization".to_owned(),
        }
        .into());
    }

    // Create an external_cells/extension_repo/{canonical_name} symlink under the
    // workspace output base
    // pointing to bazel-external/{canonical_name}. `resolve_external_cell_source`
    // in buck_out_path.rs builds action command lines that reference source files
    // at the output-base path (mirroring how bzlmod cells get a parallel symlink
    // in legacy_configs/cells.rs). Without this, gcc/clang can't find the actual
    // files.
    ensure_output_base_extension_repo_symlink(
        &project_root_path,
        extension_lookup_workspace_id.output_base.as_ref(),
        &setup.canonical_name,
    );

    Ok(Arc::new(ExtensionRepoFileOpsDelegate::new(
        cell_name,
        setup.canonical_name.to_string(),
        source_path,
        digest_config,
    )))
}

/// Create `external_cells/extension_repo/{canonical_name}` under the workspace
/// output base as a symlink to `bazel-external/{canonical_name}` (the
/// materialized repo content).
///
/// Action command lines reference sources via the buck-out path computed in
/// `BuckOutPathResolver::resolve_external_cell_source`. Materialization writes
/// content under `bazel-external/`, so a symlink bridges the two locations.
/// Failures are logged but non-fatal; downstream action execution will surface
/// the missing-file error with the full command context.
fn ensure_output_base_extension_repo_symlink(
    project_root: &std::path::Path,
    output_base: &std::path::Path,
    canonical_name: &str,
) {
    let source = project_root.join("bazel-external").join(canonical_name);
    let link_parent = output_base.join("external_cells/extension_repo");
    let link = link_parent.join(canonical_name);

    if let Ok(existing) = std::fs::read_link(&link) {
        if existing == source {
            return;
        }
        if let Err(e) = std::fs::remove_file(&link) {
            tracing::warn!(
                "Failed to remove stale extension_repo symlink {:?}: {}",
                link,
                e
            );
            return;
        }
    } else if link.exists() {
        tracing::warn!(
            "external_cells/extension_repo/{} exists and is not a symlink under {:?} — skipping",
            canonical_name,
            link_parent
        );
        return;
    }

    if let Err(e) = std::fs::create_dir_all(&link_parent) {
        tracing::warn!(
            "Failed to create extension_repo symlink parent {:?}: {}",
            link_parent,
            e
        );
        return;
    }

    #[cfg(unix)]
    let sym_res = std::os::unix::fs::symlink(&source, &link);
    #[cfg(windows)]
    let sym_res = std::os::windows::fs::symlink_dir(&source, &link);

    if let Err(e) = sym_res {
        tracing::warn!(
            "Failed to create extension_repo symlink {:?} -> {:?}: {}",
            link,
            source,
            e
        );
    }
}

/// Copy extension repository content to destination.
///
/// This is used by the expand function to copy the materialized repository content
/// into the project's external directory.
///
/// Note: This function cannot trigger lazy materialization because it doesn't
/// have access to DICE. The caller should ensure the repo is materialized
/// (via `get_file_ops_delegate`) before calling this function.
pub(crate) async fn copy_to_destination(
    setup: &ExtensionRepoCellSetup,
    project_root: &slug_fs::paths::abs_norm_path::AbsNormPath,
    dest_path: &std::path::Path,
) -> slug_error::Result<()> {
    // Compute source path from canonical name
    let source_path = project_root
        .as_path()
        .join("bazel-external")
        .join(setup.canonical_name.as_ref());

    // Check if materialized
    if !source_path.exists() {
        return Err(ExtensionRepoError::NotMaterialized {
            canonical_name: setup.canonical_name.to_string(),
            extension_id: setup.extension_id.to_string(),
        }
        .into());
    }

    // Copy recursively using the same helper as repository_rule
    crate::repository_rule::copy_to_destination_impl(&source_path, dest_path).await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn extension_spoke_lookup_uses_injected_workspace_identity() -> slug_error::Result<()> {
        let project_root = std::env::temp_dir().join(format!(
            "slug-spoke-lookup-workspace-{}",
            std::process::id()
        ));
        let output_base =
            std::env::temp_dir().join(format!("slug-spoke-lookup-output-{}", std::process::id()));
        let workspace_id = slug_bzlmod::WorkspaceId::new(project_root.clone(), output_base);
        let injected = Arc::new(slug_bzlmod::BzlmodCellGraphValue::empty_for_workspace(
            workspace_id.clone(),
        ));

        let dice = dice::testing::DiceBuilder::new()
            .build(dice::UserComputationData::new())
            .unwrap()
            .commit()
            .await;
        let mut updater = dice.into_updater();
        updater.changed_to(vec![(slug_bzlmod::BzlmodCellGraphDataKey, injected)])?;
        let mut dice = updater.commit().await;

        let actual = workspace_id_for_extension_spoke_lookup(&mut dice, "_main+ext+tool").await?;

        assert_eq!(actual, workspace_id);
        assert_ne!(
            actual,
            slug_bzlmod::WorkspaceId::new(project_root.clone(), project_root.join("buck-out/v2"))
        );

        Ok(())
    }

    #[test]
    fn extension_repo_symlink_uses_workspace_output_base() {
        let base = std::env::temp_dir().join(format!("slug-extension-link-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&base);
        let project_root = base.join("project");
        let output_base = base.join("custom-output");
        let source = project_root.join("bazel-external/_main+ext+repo");
        std::fs::create_dir_all(&source).unwrap();

        ensure_output_base_extension_repo_symlink(&project_root, &output_base, "_main+ext+repo");

        let explicit_link = output_base.join("external_cells/extension_repo/_main+ext+repo");
        assert_eq!(std::fs::read_link(explicit_link).unwrap(), source);
        assert!(
            !project_root
                .join("buck-out/v2/external_cells/extension_repo/_main+ext+repo")
                .exists()
        );

        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn complete_marker_detection_requires_current_spec_hash_when_available() {
        let base =
            std::env::temp_dir().join(format!("slug-complete-marker-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&base);
        let repo = base.join("repo");
        std::fs::create_dir_all(&repo).unwrap();
        std::fs::write(repo.join("data.txt"), "fresh").unwrap();
        assert!(complete_marker_matches("complete", ""));
        assert!(complete_marker_matches(
            "complete:sha256-new:output:sha256-out\n",
            "sha256-new"
        ));
        assert!(!complete_marker_matches("complete", "sha256-new"));
        assert!(!complete_marker_matches(
            "complete:sha256-old",
            "sha256-new"
        ));
        assert!(!complete_marker_matches(
            "complete:sha256-old:output:sha256-out",
            "sha256-new"
        ));
        assert!(is_complete_marker("complete"));
        assert!(is_complete_marker("complete:sha256-old"));
        assert!(is_complete_marker("complete:sha256-old:output:sha256-out"));
        assert!(!is_output_state_marker("complete"));
        assert!(!is_output_state_marker("complete:sha256-old"));
        assert!(is_output_state_marker(
            "complete:sha256-old:output:sha256-out"
        ));
        let output_digest = slug_bzlmod::repository_output_digest(&repo).unwrap();
        let marker = complete_marker("sha256-new", Some(&output_digest));
        assert_eq!(
            complete_marker_expected_output(&marker, "sha256-new"),
            Some(output_digest.as_str())
        );
        assert!(!complete_marker_output_state_is_stale(
            &repo,
            &marker,
            "sha256-new"
        ));
        std::fs::write(repo.join("data.txt"), "corrupt").unwrap();
        assert!(complete_marker_output_state_is_stale(
            &repo,
            &marker,
            "sha256-new"
        ));
        assert!(!is_complete_marker("stub:sha256-old"));
        let _ = std::fs::remove_dir_all(&base);
    }

    #[tokio::test]
    async fn no_spec_complete_marker_does_not_skip_dice_execution() -> slug_error::Result<()> {
        use slug_bzlmod::SetBzlmodSessionData;
        use slug_common::dice::data::testing::SetTestingIoProvider;
        use slug_core::fs::project::ProjectRootTemp;
        use slug_execute::digest_config::SetDigestConfig;

        let fs = ProjectRootTemp::new()?;
        let canonical_name = "+local_repository+stale";
        let source_path = fs
            .path()
            .root()
            .as_path()
            .join("bazel-external")
            .join(canonical_name);
        std::fs::create_dir_all(&source_path)?;
        std::fs::write(source_path.join(".slug_repo_complete"), "complete\n")?;

        let workspace_id = slug_bzlmod::WorkspaceId::new(
            fs.path().root().to_path_buf(),
            fs.path().root().as_path().join("buck-out/custom-output"),
        );
        let dice = dice::testing::DiceBuilder::new()
            .set_data(|data| {
                data.set_testing_io_provider(&fs);
                data.set_digest_config(DigestConfig::testing_default());
            })
            .build(dice::UserComputationData::new())
            .unwrap()
            .commit()
            .await;
        let mut updater = dice.into_updater();
        updater
            .set_bzlmod_session_data(slug_bzlmod::BzlmodSessionData::for_workspace(workspace_id))?;
        let mut dice = updater.commit().await;

        let setup = ExtensionRepoCellSetup {
            canonical_name: Arc::from(canonical_name),
            extension_id: Arc::from(
                "@bazel_tools//tools/build_defs/repo:local.bzl%local_repository",
            ),
            internal_name: Arc::from("stale"),
            spec_hash: Arc::from(""),
            repo_spec_json: Arc::from(""),
            repo_env_json: Arc::from(""),
            materialized: false,
        };

        let result =
            get_file_ops_delegate(&mut dice, CellName::testing_new(canonical_name), setup).await;

        assert!(
            result.is_err(),
            "no-spec extension repos must enter DICE execution instead of trusting an existing complete marker"
        );

        Ok(())
    }
}
