mod action_environment;
mod cache_grammar;
mod configuration;
mod configuration_field;
mod convert;
mod cpp_fragment;
mod defaults;
pub mod host;
mod label_convert;
mod matching;
mod path;
mod registry;
mod value;

#[cfg(test)]
mod tests;

pub use action_environment::CanonicalStringMap;
pub use action_environment::CanonicalStringSet;
pub use action_environment::RetainedActionEnvironment;
pub use cache_grammar::CacheFieldValue;
pub use cache_grammar::format_cache_field;
pub use configuration::NativeStringListOption;
pub use configuration::PreparedCommandNativeOptions;
pub use configuration::SlugConfiguration;
pub use configuration::SlugConfigurationError;
pub use configuration::SlugConfigurationKind;
pub use configuration::SlugConfigurationProjection;
pub use configuration::StarlarkOption;
pub use configuration::StarlarkOptionScope;
pub use configuration::StarlarkOptionValue;
pub use configuration::StarlarkOptions;
pub use configuration_field::ConfigurationField;
pub use configuration_field::ConfigurationFieldIdentity;
pub use configuration_field::CoverageConfigurationField;
pub use configuration_field::CppConfigurationField;
pub use cpp_fragment::CppFragmentProjection;
pub use matching::NativeConfigSettingMatchError;
pub use path::BazelPathError;
pub use path::NormalizedAbsoluteBazelPath;
pub use path::NormalizedBazelPath;
pub use registry::NATIVE_OPTION_DESCRIPTORS;
pub use registry::NativeOptionDescriptor;
