print("ROOT_INCLUDE_EVENT_DEPS_BEFORE")
include("//:nested.MODULE.bazel")
print("ROOT_INCLUDE_EVENT_DEPS_BETWEEN")
include("//:nested.MODULE.bazel")
print("ROOT_INCLUDE_EVENT_DEPS_AFTER")
bazel_dep(name = "dep", repo_name = "dep_alias", version = "1.0.0")
local_path_override(module_name = "dep", path = "modules/dep_one")
