/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

//! Generate source files containing bundled cell contents (prelude, bazel_tools).

use std::io;
use std::path::Path;

fn main() {
    imp().unwrap();
}

fn imp() -> io::Result<()> {
    let out_path = std::env::var_os("OUT_DIR").unwrap();
    let out_dir = Path::new(&out_path);
    let manifest_path = std::env::var_os("CARGO_MANIFEST_DIR").unwrap();
    let project_root = Path::new(&manifest_path)
        .parent()
        .unwrap()
        .parent()
        .unwrap();

    // Generate prelude bundled files
    let prelude_path = project_root.join("prelude");
    assert!(
        prelude_path.join("prelude.bzl").exists(),
        "prelude/prelude.bzl not found"
    );
    println!("cargo:rerun-if-changed={}", prelude_path.display());
    write_include_file(
        &prelude_path,
        std::fs::File::create(out_dir.join("prelude_include.rs"))?,
    )?;

    // Generate bazel_tools bundled files
    let bazel_tools_path = project_root.join("bazel_tools");
    assert!(
        bazel_tools_path
            .join("tools/build_defs/repo/http.bzl")
            .exists(),
        "bazel_tools/tools/build_defs/repo/http.bzl not found"
    );
    println!("cargo:rerun-if-changed={}", bazel_tools_path.display());
    write_include_file(
        &bazel_tools_path,
        std::fs::File::create(out_dir.join("bazel_tools_include.rs"))?,
    )?;

    // Generate local_config_platform bundled files
    // This is a Bazel auto-generated repo providing HOST_CONSTRAINTS for the current platform.
    let local_config_platform_out = out_dir.join("local_config_platform_src");
    std::fs::create_dir_all(&local_config_platform_out)?;

    let os_constraint = match std::env::consts::OS {
        "linux" => "@platforms//os:linux",
        "macos" => "@platforms//os:osx",
        "windows" => "@platforms//os:windows",
        _ => "@platforms//os:linux",
    };
    let cpu_constraint = match std::env::consts::ARCH {
        "x86_64" => "@platforms//cpu:x86_64",
        "aarch64" => "@platforms//cpu:aarch64",
        _ => "@platforms//cpu:x86_64",
    };
    let constraints_content =
        format!("HOST_CONSTRAINTS = [\n    \"{cpu_constraint}\",\n    \"{os_constraint}\",\n]\n");
    std::fs::write(
        local_config_platform_out.join("constraints.bzl"),
        &constraints_content,
    )?;

    // Generate BUILD.bazel for local_config_platform with a platform() target
    // that uses the auto-detected host OS/CPU constraints.
    // This mirrors what Bazel's auto-generated @local_config_platform//:host provides.
    let build_content = "load(\":constraints.bzl\", \"HOST_CONSTRAINTS\")\n\nplatform(\n    name = \"host\",\n    constraint_values = HOST_CONSTRAINTS,\n)\n";
    std::fs::write(local_config_platform_out.join("BUILD.bazel"), build_content)?;

    write_include_file(
        &local_config_platform_out,
        std::fs::File::create(out_dir.join("local_config_platform_include.rs"))?,
    )?;

    Ok(())
}

fn as_unix_like(path: &Path) -> String {
    path.to_str().unwrap().replace('\\', "/")
}

fn write_include_file(prelude: &Path, mut include_file: impl io::Write) -> io::Result<()> {
    #[allow(clippy::write_literal)]
    writeln!(include_file, "// {}generated by crate build.rs", "@")?;

    writeln!(
        include_file,
        "pub(crate) const DATA: &[crate::BundledFile] = &["
    )?;

    for res in walkdir::WalkDir::new(prelude) {
        let entry = res.map_err(|e| e.into_io_error().unwrap())?;
        if !entry.file_type().is_file() {
            continue;
        }

        writeln!(include_file, "crate::BundledFile {{")?;
        writeln!(
            include_file,
            "  path: r\"{}\",",
            as_unix_like(entry.path().strip_prefix(prelude).unwrap())
        )?;
        writeln!(
            include_file,
            "  contents: include_bytes!(r\"{}\"),",
            entry.path().display()
        )?;

        let exec_bit;
        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt;
            exec_bit = entry.metadata()?.mode() & 0o111 != 0;
        }
        #[cfg(not(unix))]
        {
            exec_bit = false;
        }

        writeln!(include_file, "  is_executable: {exec_bit},")?;
        writeln!(include_file, "}},")?;
    }

    writeln!(include_file, "];")?;
    Ok(())
}
