/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

//! Extension repository external cell implementation.
//!
//! Extension-generated repositories are created by module extensions (e.g., pip.parse(),
//! go_deps, maven.install()). They use a deferred execution model:
//!
//! 1. During extension evaluation, `RepoSpec` objects are captured (no downloads)
//! 2. When a repo is first accessed, the `RepoSpec` is executed to materialize it
//! 3. Materialized repos are stored at `bazel-external/{canonical_name}`
//!
//! This module provides file operations for extension repos. If a repo isn't
//! materialized yet, operations will fail with an error indicating lazy execution
//! is needed (full lazy execution wiring is done at a higher level).

use std::path::PathBuf;
use std::sync::Arc;

use async_trait::async_trait;
use cmp_any::PartialEqAny;
use compact_str::CompactString;
use dice::DiceComputations;
use kuro_common::dice::data::HasIoProvider;
use kuro_common::external_symlink::ExternalSymlink;
use kuro_common::file_ops::delegate::FileOpsDelegate;
use kuro_common::file_ops::dice::ReadFileProxy;
use kuro_common::file_ops::metadata::FileMetadata;
use kuro_common::file_ops::metadata::FileType;
use kuro_common::file_ops::metadata::RawDirEntry;
use kuro_common::file_ops::metadata::RawPathMetadata;
use kuro_common::file_ops::metadata::RawSymlink;
use kuro_common::file_ops::metadata::TrackedFileDigest;
use kuro_core::cells::cell_path::CellPath;
use kuro_core::cells::external::ExtensionRepoCellSetup;
use kuro_core::cells::name::CellName;
use kuro_core::cells::paths::CellRelativePath;
use kuro_core::cells::paths::CellRelativePathBuf;
use kuro_execute::digest_config::DigestConfig;
use kuro_execute::digest_config::HasDigestConfig;
use kuro_fs::paths::forward_rel_path::ForwardRelativePathBuf;

/// Error for extension repos that haven't been materialized yet.
#[derive(Debug, kuro_error::Error)]
#[kuro(tag = Input)]
pub enum ExtensionRepoError {
    #[error(
        "Extension repository '{}' has not been materialized yet. \
         This repo is generated by extension '{}' and needs to be lazily executed.",
        canonical_name, extension_id
    )]
    NotMaterialized {
        canonical_name: String,
        extension_id: String,
    },
}

/// File operations delegate for extension-generated repositories.
///
/// This delegate reads files from the materialized repository path
/// (typically `bazel-external/{canonical_name}`).
#[derive(allocative::Allocative)]
pub(crate) struct ExtensionRepoFileOpsDelegate {
    /// The cell name.
    cell_name: CellName,
    /// The canonical name of the repository (e.g., "_main~pip~numpy").
    /// Kept for debugging and error messages.
    #[allow(dead_code)]
    canonical_name: String,
    /// The absolute path to the materialized repository content.
    source_path: PathBuf,
    /// Digest config for computing file digests.
    digest_config: DigestConfig,
}

impl ExtensionRepoFileOpsDelegate {
    pub fn new(
        cell_name: CellName,
        canonical_name: String,
        source_path: PathBuf,
        digest_config: DigestConfig,
    ) -> Self {
        Self {
            cell_name,
            canonical_name,
            source_path,
            digest_config,
        }
    }

    fn resolve_path(&self, path: &CellRelativePath) -> PathBuf {
        self.source_path.join(path.as_str())
    }

    fn make_cell_path(&self, path: &CellRelativePath) -> Arc<CellPath> {
        Arc::new(CellPath::new(
            self.cell_name,
            CellRelativePathBuf::from(path.to_owned()),
        ))
    }
}

#[async_trait]
impl FileOpsDelegate for ExtensionRepoFileOpsDelegate {
    async fn read_file_if_exists(
        &self,
        _ctx: &mut DiceComputations<'_>,
        path: &'async_trait CellRelativePath,
    ) -> kuro_error::Result<ReadFileProxy> {
        let abs_path = self.resolve_path(path);
        Ok(ReadFileProxy::new_with_captures(abs_path, |abs_path| async move {
            match tokio::fs::read_to_string(&abs_path).await {
                Ok(contents) => Ok(Some(contents)),
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
                Err(e) => Err(kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to read extension repo file {:?}: {}",
                    abs_path,
                    e
                )),
            }
        }))
    }

    async fn read_dir(
        &self,
        _ctx: &mut DiceComputations<'_>,
        path: &'async_trait CellRelativePath,
    ) -> kuro_error::Result<Arc<[RawDirEntry]>> {
        let abs_path = self.resolve_path(path);

        let mut entries = Vec::new();
        let mut read_dir = tokio::fs::read_dir(&abs_path).await.map_err(|e| {
            kuro_error::kuro_error!(
                kuro_error::ErrorTag::Environment,
                "Failed to read extension repo directory {:?}: {}",
                abs_path,
                e
            )
        })?;

        while let Some(entry) = read_dir.next_entry().await.map_err(|e| {
            kuro_error::kuro_error!(
                kuro_error::ErrorTag::Environment,
                "Failed to read directory entry: {}",
                e
            )
        })? {
            let file_type = entry.file_type().await.map_err(|e| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to get file type: {}",
                    e
                )
            })?;

            let file_name = entry.file_name().into_string().map_err(|_| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Non-UTF8 filename in {:?}",
                    abs_path
                )
            })?;

            entries.push(RawDirEntry {
                file_name: CompactString::from(file_name),
                file_type: if file_type.is_dir() {
                    FileType::Directory
                } else if file_type.is_symlink() {
                    FileType::Symlink
                } else {
                    FileType::File
                },
            });
        }

        // Sort entries for deterministic output
        entries.sort_by(|a, b| a.file_name.cmp(&b.file_name));

        Ok(entries.into())
    }

    async fn read_path_metadata_if_exists(
        &self,
        _ctx: &mut DiceComputations<'_>,
        path: &'async_trait CellRelativePath,
    ) -> kuro_error::Result<Option<RawPathMetadata>> {
        let abs_path = self.resolve_path(path);

        let metadata = match tokio::fs::symlink_metadata(&abs_path).await {
            Ok(m) => m,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(e) => {
                return Err(kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to get metadata for extension repo file {:?}: {}",
                    abs_path,
                    e
                ))
            }
        };

        if metadata.is_dir() {
            Ok(Some(RawPathMetadata::Directory))
        } else if metadata.is_symlink() {
            // Read symlink target
            let target = tokio::fs::read_link(&abs_path).await.map_err(|e| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to read symlink {:?}: {}",
                    abs_path,
                    e
                )
            })?;

            let cell_path = self.make_cell_path(path);

            // Treat symlinks as external
            let external = ExternalSymlink::new(target, ForwardRelativePathBuf::empty())?;
            Ok(Some(RawPathMetadata::Symlink {
                at: cell_path,
                to: RawSymlink::External(Arc::new(external)),
            }))
        } else {
            // Regular file
            let contents = tokio::fs::read(&abs_path).await.map_err(|e| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to read extension repo file {:?}: {}",
                    abs_path,
                    e
                )
            })?;

            let source_config = self
                .digest_config
                .cas_digest_config()
                .source_files_config();
            let digest = TrackedFileDigest::from_content(&contents, source_config);

            #[cfg(unix)]
            let is_executable = {
                use std::os::unix::fs::PermissionsExt;
                metadata.permissions().mode() & 0o111 != 0
            };
            #[cfg(not(unix))]
            let is_executable = false;

            Ok(Some(RawPathMetadata::File(FileMetadata {
                digest,
                is_executable,
            })))
        }
    }

    fn eq_token(&self) -> PartialEqAny<'_> {
        PartialEqAny::always_false()
    }
}

/// Get the file ops delegate for an extension-generated repository cell.
///
/// This computes the expected path for the materialized repository
/// (`bazel-external/{canonical_name}`) and checks if it exists.
///
/// If the repository hasn't been materialized yet, this returns an error.
/// The higher-level code should handle this by triggering lazy execution
/// via `ExtensionRepoExecutionKey`.
pub(crate) async fn get_file_ops_delegate(
    ctx: &mut DiceComputations<'_>,
    cell_name: CellName,
    setup: ExtensionRepoCellSetup,
) -> kuro_error::Result<Arc<dyn FileOpsDelegate>> {
    let digest_config = ctx.global_data().get_digest_config();

    // Compute the expected path for the materialized repository
    let io = ctx.global_data().get_io_provider();
    let project_root = io.project_root();
    let source_path = project_root
        .root()
        .as_path()
        .join("bazel-external")
        .join(setup.canonical_name.as_ref());

    // Check if the repository is materialized
    if !setup.materialized {
        // The repo hasn't been materialized yet
        // The higher-level code should trigger lazy execution
        return Err(ExtensionRepoError::NotMaterialized {
            canonical_name: setup.canonical_name.to_string(),
            extension_id: setup.extension_id.to_string(),
        }
        .into());
    }

    // Verify the source path exists
    if !source_path.exists() {
        return Err(ExtensionRepoError::NotMaterialized {
            canonical_name: setup.canonical_name.to_string(),
            extension_id: setup.extension_id.to_string(),
        }
        .into());
    }

    Ok(Arc::new(ExtensionRepoFileOpsDelegate::new(
        cell_name,
        setup.canonical_name.to_string(),
        source_path,
        digest_config,
    )))
}

/// Copy extension repository content to destination.
///
/// This is used by the expand function to copy the materialized repository content
/// into the project's external directory.
pub(crate) async fn copy_to_destination(
    setup: &ExtensionRepoCellSetup,
    project_root: &kuro_fs::paths::abs_norm_path::AbsNormPath,
    dest_path: &std::path::Path,
) -> kuro_error::Result<()> {
    // Compute source path from canonical name
    let source_path = project_root
        .as_path()
        .join("bazel-external")
        .join(setup.canonical_name.as_ref());

    // Check if materialized
    if !setup.materialized || !source_path.exists() {
        return Err(ExtensionRepoError::NotMaterialized {
            canonical_name: setup.canonical_name.to_string(),
            extension_id: setup.extension_id.to_string(),
        }
        .into());
    }

    // Copy recursively using the same helper as repository_rule
    crate::repository_rule::copy_to_destination_impl(&source_path, dest_path).await
}
