/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

//! Extension repository external cell implementation.
//!
//! Extension-generated repositories are created by module extensions (e.g., pip.parse(),
//! go_deps, maven.install()). They use a deferred execution model:
//!
//! 1. During extension evaluation, `RepoSpec` objects are captured (no downloads)
//! 2. When a repo is first accessed, the `RepoSpec` is executed to materialize it
//! 3. Materialized repos are stored at `bazel-external/{canonical_name}`
//!
//! This module provides file operations for extension repos. When a repo isn't
//! materialized yet, lazy materialization is triggered via `ExtensionRepoExecutionKey`.

use std::path::PathBuf;
use std::sync::Arc;

use async_trait::async_trait;
use cmp_any::PartialEqAny;
use compact_str::CompactString;
use dice::DiceComputations;
use kuro_bzlmod::ExtensionRepoExecutionKey;
use kuro_bzlmod::RepoSpec;
use kuro_common::dice::data::HasIoProvider;
use kuro_common::external_symlink::ExternalSymlink;
use kuro_common::file_ops::delegate::FileOpsDelegate;
use kuro_common::file_ops::dice::ReadFileProxy;
use kuro_common::file_ops::metadata::FileMetadata;
use kuro_common::file_ops::metadata::FileType;
use kuro_common::file_ops::metadata::RawDirEntry;
use kuro_common::file_ops::metadata::RawPathMetadata;
use kuro_common::file_ops::metadata::RawSymlink;
use kuro_common::file_ops::metadata::TrackedFileDigest;
use kuro_core::cells::cell_path::CellPath;
use kuro_core::cells::external::ExtensionRepoCellSetup;
use kuro_core::cells::external::ExternalCellOrigin;
use kuro_core::cells::name::CellName;
use kuro_core::cells::paths::CellRelativePath;
use kuro_core::cells::paths::CellRelativePathBuf;
use kuro_execute::digest_config::DigestConfig;
use kuro_execute::digest_config::HasDigestConfig;
use kuro_execute::materialize::materializer::HasMaterializer;
use kuro_execute::materialize::materializer::WriteRequest;
use kuro_fs::paths::forward_rel_path::ForwardRelativePathBuf;

/// Error for extension repos.
#[derive(Debug, kuro_error::Error)]
#[kuro(tag = Input)]
pub enum ExtensionRepoError {
    #[error(
        "Extension repository '{}' has not been materialized yet. \
         This repo is generated by extension '{}' and needs to be lazily executed.",
        canonical_name,
        extension_id
    )]
    NotMaterialized {
        canonical_name: String,
        extension_id: String,
    },

    #[error(
        "Failed to deserialize RepoSpec for extension repository '{}': {}",
        canonical_name,
        reason
    )]
    DeserializationFailed {
        canonical_name: String,
        reason: String,
    },

    #[error(
        "Failed to materialize extension repository '{}': {}",
        canonical_name,
        reason
    )]
    MaterializationFailed {
        canonical_name: String,
        reason: String,
    },
}

/// File operations delegate for extension-generated repositories.
///
/// This delegate reads files from the materialized repository path
/// (typically `bazel-external/{canonical_name}`).
#[derive(allocative::Allocative)]
pub(crate) struct ExtensionRepoFileOpsDelegate {
    /// The cell name.
    cell_name: CellName,
    /// The canonical name of the repository (e.g., "_main+pip+numpy").
    /// Kept for debugging and error messages.
    #[allow(dead_code)]
    canonical_name: String,
    /// The absolute path to the materialized repository content.
    source_path: PathBuf,
    /// Digest config for computing file digests.
    digest_config: DigestConfig,
}

impl ExtensionRepoFileOpsDelegate {
    pub fn new(
        cell_name: CellName,
        canonical_name: String,
        source_path: PathBuf,
        digest_config: DigestConfig,
    ) -> Self {
        Self {
            cell_name,
            canonical_name,
            source_path,
            digest_config,
        }
    }

    fn resolve_path(&self, path: &CellRelativePath) -> PathBuf {
        self.source_path.join(path.as_str())
    }

    fn make_cell_path(&self, path: &CellRelativePath) -> Arc<CellPath> {
        Arc::new(CellPath::new(
            self.cell_name,
            CellRelativePathBuf::from(path.to_owned()),
        ))
    }
}

#[async_trait]
impl FileOpsDelegate for ExtensionRepoFileOpsDelegate {
    async fn read_file_if_exists(
        &self,
        _ctx: &mut DiceComputations<'_>,
        path: &'async_trait CellRelativePath,
    ) -> kuro_error::Result<ReadFileProxy> {
        let abs_path = self.resolve_path(path);
        Ok(ReadFileProxy::new_with_captures(
            abs_path,
            |abs_path| async move {
                match tokio::fs::read_to_string(&abs_path).await {
                    Ok(contents) => Ok(Some(contents)),
                    Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
                    Err(e) => Err(kuro_error::kuro_error!(
                        kuro_error::ErrorTag::Environment,
                        "Failed to read extension repo file {:?}: {}",
                        abs_path,
                        e
                    )),
                }
            },
        ))
    }

    async fn read_dir(
        &self,
        _ctx: &mut DiceComputations<'_>,
        path: &'async_trait CellRelativePath,
    ) -> kuro_error::Result<Arc<[RawDirEntry]>> {
        let abs_path = self.resolve_path(path);

        let mut entries = Vec::new();
        let mut read_dir = tokio::fs::read_dir(&abs_path).await.map_err(|e| {
            kuro_error::kuro_error!(
                kuro_error::ErrorTag::Environment,
                "Failed to read extension repo directory {:?}: {}",
                abs_path,
                e
            )
        })?;

        while let Some(entry) = read_dir.next_entry().await.map_err(|e| {
            kuro_error::kuro_error!(
                kuro_error::ErrorTag::Environment,
                "Failed to read directory entry: {}",
                e
            )
        })? {
            let file_type = entry.file_type().await.map_err(|e| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to get file type: {}",
                    e
                )
            })?;

            let file_name = entry.file_name().into_string().map_err(|_| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Non-UTF8 filename in {:?}",
                    abs_path
                )
            })?;

            entries.push(RawDirEntry {
                file_name: CompactString::from(file_name),
                file_type: if file_type.is_dir() {
                    FileType::Directory
                } else if file_type.is_symlink() {
                    FileType::Symlink
                } else {
                    FileType::File
                },
            });
        }

        // Sort entries for deterministic output
        entries.sort_by(|a, b| a.file_name.cmp(&b.file_name));

        Ok(entries.into())
    }

    async fn read_path_metadata_if_exists(
        &self,
        _ctx: &mut DiceComputations<'_>,
        path: &'async_trait CellRelativePath,
    ) -> kuro_error::Result<Option<RawPathMetadata>> {
        let abs_path = self.resolve_path(path);

        let metadata = match tokio::fs::symlink_metadata(&abs_path).await {
            Ok(m) => m,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(e) => {
                return Err(kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to get metadata for extension repo file {:?}: {}",
                    abs_path,
                    e
                ));
            }
        };

        if metadata.is_dir() {
            Ok(Some(RawPathMetadata::Directory))
        } else if metadata.is_symlink() {
            // Read symlink target
            let target = tokio::fs::read_link(&abs_path).await.map_err(|e| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to read symlink {:?}: {}",
                    abs_path,
                    e
                )
            })?;

            let cell_path = self.make_cell_path(path);

            // Treat symlinks as external
            let external = ExternalSymlink::new(target, ForwardRelativePathBuf::empty())?;
            Ok(Some(RawPathMetadata::Symlink {
                at: cell_path,
                to: RawSymlink::External(Arc::new(external)),
            }))
        } else {
            // Regular file
            let contents = tokio::fs::read(&abs_path).await.map_err(|e| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to read extension repo file {:?}: {}",
                    abs_path,
                    e
                )
            })?;

            let source_config = self.digest_config.cas_digest_config().source_files_config();
            let digest = TrackedFileDigest::from_content(&contents, source_config);

            #[cfg(unix)]
            let is_executable = {
                use std::os::unix::fs::PermissionsExt;
                metadata.permissions().mode() & 0o111 != 0
            };
            #[cfg(not(unix))]
            let is_executable = false;

            Ok(Some(RawPathMetadata::File(FileMetadata {
                digest,
                is_executable,
            })))
        }
    }

    fn eq_token(&self) -> PartialEqAny<'_> {
        PartialEqAny::always_false()
    }
}

/// Get the file ops delegate for an extension-generated repository cell.
///
/// This computes the expected path for the materialized repository
/// (`bazel-external/{canonical_name}`) and triggers lazy materialization
/// if the repository hasn't been materialized yet.
///
/// ## Lazy Materialization Flow
///
/// 1. Check if the repository is already materialized (exists on disk)
/// 2. If not materialized, deserialize the `RepoSpec` from `repo_spec_json`
/// Declare all source files from an extension repo with the materializer.
async fn declare_all_source_artifacts_ext(
    ctx: &mut DiceComputations<'_>,
    setup: &ExtensionRepoCellSetup,
    source_path: &std::path::Path,
) -> kuro_error::Result<()> {
    let artifact_fs =
        kuro_build_api::actions::artifact::get_artifact_fs::GetArtifactFs::get_artifact_fs(ctx)
            .await?;
    let buck_out_resolver = artifact_fs.buck_out_path_resolver();

    let mut requests = Vec::new();
    let mut stack: Vec<PathBuf> = vec![source_path.to_path_buf()];

    while let Some(dir) = stack.pop() {
        let mut read_dir = match tokio::fs::read_dir(&dir).await {
            Ok(rd) => rd,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => continue,
            Err(e) => {
                return Err(kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to read extension repo directory {:?}: {}",
                    dir,
                    e
                ));
            }
        };

        while let Some(entry) = read_dir.next_entry().await.map_err(|e| {
            kuro_error::kuro_error!(
                kuro_error::ErrorTag::Environment,
                "Failed to read directory entry: {}",
                e
            )
        })? {
            let file_type = entry.file_type().await.map_err(|e| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to get file type: {}",
                    e
                )
            })?;

            if file_type.is_dir() {
                stack.push(entry.path());
                continue;
            }

            if !file_type.is_file() {
                continue;
            }

            let abs_path = entry.path();
            let rel = abs_path.strip_prefix(source_path).map_err(|e| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to compute relative path: {}",
                    e
                )
            })?;
            let rel_str = rel.to_string_lossy().replace('\\', "/");
            let cell_rel = CellRelativePath::unchecked_new(&rel_str);

            let path = buck_out_resolver.resolve_external_cell_source(
                cell_rel,
                ExternalCellOrigin::ExtensionRepo(setup.clone()),
            );

            let content = tokio::fs::read(&abs_path).await.map_err(|e| {
                kuro_error::kuro_error!(
                    kuro_error::ErrorTag::Environment,
                    "Failed to read extension repo file {:?}: {}",
                    abs_path,
                    e
                )
            })?;

            requests.push(WriteRequest {
                path,
                content,
                is_executable: false,
            });
        }
    }

    if !requests.is_empty() {
        let materializer = ctx.per_transaction_data().get_materializer();
        materializer
            .declare_write(Box::new(move || Ok(requests)))
            .await
            .map(|_| ())?;
    }

    Ok(())
}

/// 3. Create and compute `ExtensionRepoExecutionKey` via DICE
/// 4. This executes the repository rule (e.g., http_archive) and materializes the repo
/// 5. Return a file ops delegate pointing to the materialized content
pub(crate) async fn get_file_ops_delegate(
    ctx: &mut DiceComputations<'_>,
    cell_name: CellName,
    setup: ExtensionRepoCellSetup,
) -> kuro_error::Result<Arc<dyn FileOpsDelegate>> {
    let digest_config = ctx.global_data().get_digest_config();

    // Compute the expected path for the materialized repository
    let io = ctx.global_data().get_io_provider();
    let project_root = io.project_root();
    let project_root_path = project_root.root().to_path_buf();
    let source_path = project_root_path
        .join("bazel-external")
        .join(setup.canonical_name.as_ref());

    // Check if the repository is fully materialized (marked complete).
    // We check for .kuro_repo_complete rather than just directory existence because
    // partial materialization (e.g., source downloaded but BUILD.bazel not generated)
    // can leave directories without the completion marker.
    if !source_path.join(".kuro_repo_complete").exists() {
        tracing::warn!(
            "Extension repo '{}' not materialized, triggering lazy execution (ext_id='{}', repo_spec_json_empty={})",
            setup.canonical_name,
            setup.extension_id,
            setup.repo_spec_json.is_empty()
        );

        // Get the RepoSpec: either from cached JSON or by executing the extension via DICE
        let repo_spec = if !setup.repo_spec_json.is_empty() {
            // Cached RepoSpec from lockfile (populated by previous builds)
            serde_json::from_str::<RepoSpec>(&setup.repo_spec_json).map_err(|e| {
                ExtensionRepoError::DeserializationFailed {
                    canonical_name: setup.canonical_name.to_string(),
                    reason: e.to_string(),
                }
            })?
        } else {
            // No cached RepoSpec - execute the extension via DICE to get it.
            // This is the Bazel 9.0-compatible path: cells are pre-computed from
            // use_repo() declarations, and extensions execute lazily on first access.
            tracing::info!(
                "No cached RepoSpec for '{}', executing extension '{}' via DICE",
                setup.canonical_name,
                setup.extension_id
            );

            let ext_key = match kuro_bzlmod::create_extension_execution_key(&setup.extension_id) {
                Some(key) => key,
                None => {
                    // Not a module extension — likely a use_repo_rule() invocation.
                    // Execute directly as a Starlark repository rule via DICE.
                    tracing::info!(
                        "Extension '{}' not in aggregations, treating as use_repo_rule for '{}'",
                        setup.extension_id,
                        setup.canonical_name
                    );
                    let mut inv = kuro_bzlmod::RepositoryInvocation::new(
                        setup.canonical_name.to_string(),
                        setup
                            .extension_id
                            .split('%')
                            .last()
                            .unwrap_or("unknown")
                            .to_owned(),
                    );
                    inv.rule_source = Some(setup.extension_id.to_string());
                    let repo_spec = kuro_bzlmod::RepoSpec::new(setup.extension_id.to_string());
                    let key = ExtensionRepoExecutionKey::new(
                        setup.canonical_name.to_string(),
                        setup.extension_id.to_string(),
                        repo_spec,
                        project_root_path.clone(),
                    );
                    match ctx.compute(&key).await {
                        Ok(Ok(repo_result)) => {
                            tracing::info!(
                                "Materialized use_repo_rule repo '{}' at {:?}",
                                setup.canonical_name,
                                repo_result.repo_path
                            );
                        }
                        Ok(Err(e)) => {
                            tracing::warn!(
                                "use_repo_rule execution failed for '{}': {}. Creating stub.",
                                setup.canonical_name,
                                e
                            );
                            materialize_stub_repo(&project_root_path, &setup.canonical_name)?;
                        }
                        Err(e) => {
                            tracing::warn!(
                                "DICE error for use_repo_rule '{}': {}. Creating stub.",
                                setup.canonical_name,
                                e
                            );
                            materialize_stub_repo(&project_root_path, &setup.canonical_name)?;
                        }
                    }
                    // Skip the extension execution path below
                    if !source_path.exists() {
                        return Err(ExtensionRepoError::MaterializationFailed {
                            canonical_name: setup.canonical_name.to_string(),
                            reason: "Repository not found after use_repo_rule execution".to_owned(),
                        }
                        .into());
                    }
                    declare_all_source_artifacts_ext(ctx, &setup, &source_path).await?;
                    return Ok(Arc::new(ExtensionRepoFileOpsDelegate::new(
                        cell_name,
                        setup.canonical_name.to_string(),
                        source_path,
                        digest_config,
                    )));
                }
            };

            let ext_result = match ctx.compute(&ext_key).await {
                Ok(Ok(result)) => result,
                Ok(Err(e)) => {
                    tracing::warn!(
                        "Extension '{}' execution failed for repo '{}': {}. Creating stub.",
                        setup.extension_id,
                        setup.canonical_name,
                        e
                    );
                    // Create stub repo so loading can continue
                    materialize_stub_repo(&project_root_path, &setup.canonical_name)?;
                    declare_all_source_artifacts_ext(ctx, &setup, &source_path).await?;
                    return Ok(Arc::new(ExtensionRepoFileOpsDelegate::new(
                        cell_name,
                        setup.canonical_name.to_string(),
                        source_path.clone(),
                        digest_config,
                    )));
                }
                Err(e) => {
                    tracing::warn!(
                        "Extension '{}' DICE error for repo '{}': {}. Creating stub.",
                        setup.extension_id,
                        setup.canonical_name,
                        e
                    );
                    materialize_stub_repo(&project_root_path, &setup.canonical_name)?;
                    declare_all_source_artifacts_ext(ctx, &setup, &source_path).await?;
                    return Ok(Arc::new(ExtensionRepoFileOpsDelegate::new(
                        cell_name,
                        setup.canonical_name.to_string(),
                        source_path.clone(),
                        digest_config,
                    )));
                }
            };

            // Eagerly materialize ALL repos from this extension, not just the one
            // being requested. In Bazel, accessing any repo from an extension triggers
            // evaluation of the entire extension and materialization of all repos.
            // Spoke repos (e.g., crates__tempfile-3.26.0) are not in use_repo() and
            // thus have no ExtensionRepoCellSetup, so they'd never be lazily triggered.
            let ext_name = kuro_bzlmod::extract_extension_name(&setup.extension_id);
            let owner_module = kuro_bzlmod::extract_owning_module(&setup.extension_id);
            // Sort specs so local_repository types materialize first — other repos
            // may reference them via build_file attributes.
            let mut sorted_specs: Vec<_> = ext_result.generated_repo_specs.iter().collect();
            sorted_specs.sort_by_key(|(_, spec)| {
                let is_local = spec.repo_rule_id.ends_with("%new_local_repository")
                    || spec.repo_rule_id.ends_with("%local_repository");
                (!is_local, spec.repo_rule_id.clone())
            });
            for (internal_name, spec) in sorted_specs {
                let canonical = format!("{}+{}+{}", owner_module, ext_name, internal_name);
                let repo_dir = project_root_path.join("bazel-external").join(&canonical);

                // Register in dynamic cell registry for cell resolution
                kuro_core::cells::register_dynamic_extension_cell(
                    canonical.clone(),
                    format!("bazel-external/{}", canonical),
                );

                // Also register the internal (apparent) name as a cell alias.
                // This is needed for repo mapping: the hub repo's BUILD.bazel
                // references spoke repos by their internal name (e.g., "crates__tempfile-3.26.0")
                // which must resolve to the canonical path.
                if internal_name != &canonical {
                    kuro_core::cells::register_dynamic_extension_cell(
                        internal_name.clone(),
                        format!("bazel-external/{}", canonical),
                    );
                }

                // Skip if already materialized
                if repo_dir.join(".kuro_repo_complete").exists() {
                    continue;
                }

                let key = ExtensionRepoExecutionKey::new(
                    canonical.clone(),
                    setup.extension_id.to_string(),
                    spec.clone(),
                    project_root_path.clone(),
                );
                match ctx.compute(&key).await {
                    Ok(Ok(_)) => {
                        tracing::debug!("Materialized extension spoke repo '{}'", canonical);
                    }
                    Ok(Err(e)) => {
                        tracing::debug!("Could not materialize spoke repo '{}': {}", canonical, e);
                    }
                    Err(e) => {
                        tracing::debug!(
                            "DICE error materializing spoke repo '{}': {}",
                            canonical,
                            e
                        );
                    }
                }
            }

            match ext_result.get_repo_spec(&setup.internal_name).cloned() {
                Some(spec) => spec,
                None => {
                    // Extension didn't generate this repo. This commonly happens when an
                    // optional extension (e.g., telemetry) fails gracefully. Create a
                    // minimal stub repo so that load() calls don't crash.
                    tracing::warn!(
                        "Extension '{}' did not generate repo '{}' (available: {:?}). \
                         Creating stub repo.",
                        setup.extension_id,
                        setup.internal_name,
                        ext_result.repo_names().collect::<Vec<_>>()
                    );
                    materialize_stub_repo(&project_root_path, &setup.canonical_name)?;
                    // The stub repo is now on disk; create file ops delegate from it
                    declare_all_source_artifacts_ext(ctx, &setup, &source_path).await?;
                    return Ok(Arc::new(ExtensionRepoFileOpsDelegate::new(
                        cell_name,
                        setup.canonical_name.to_string(),
                        source_path.clone(),
                        digest_config,
                    )));
                }
            }
        };

        // Create the execution key for lazy materialization of this specific repo
        let key = ExtensionRepoExecutionKey::new(
            setup.canonical_name.to_string(),
            setup.extension_id.to_string(),
            repo_spec,
            project_root_path.clone(),
        );

        // Execute via DICE to materialize the repository
        match ctx.compute(&key).await {
            Ok(Ok(repo_result)) => {
                tracing::info!(
                    "Successfully materialized extension repo '{}' at {:?}",
                    setup.canonical_name,
                    repo_result.repo_path
                );
            }
            Ok(Err(e)) => {
                tracing::warn!(
                    "Repo rule execution failed for '{}': {}. Creating stub.",
                    setup.canonical_name,
                    e
                );
                materialize_stub_repo(&project_root_path, &setup.canonical_name)?;
            }
            Err(e) => {
                tracing::warn!(
                    "DICE computation failed for '{}': {}. Creating stub.",
                    setup.canonical_name,
                    e
                );
                materialize_stub_repo(&project_root_path, &setup.canonical_name)?;
            }
        }
    }

    // At this point, the repository should exist on disk
    if !source_path.exists() {
        return Err(ExtensionRepoError::MaterializationFailed {
            canonical_name: setup.canonical_name.to_string(),
            reason: "Repository not found after materialization".to_owned(),
        }
        .into());
    }

    // Declare all source files with the materializer so they exist
    // at buck-out/v2/external_cells/extension_repo/... paths during action execution.
    declare_all_source_artifacts_ext(ctx, &setup, &source_path).await?;

    Ok(Arc::new(ExtensionRepoFileOpsDelegate::new(
        cell_name,
        setup.canonical_name.to_string(),
        source_path,
        digest_config,
    )))
}

/// Copy extension repository content to destination.
///
/// This is used by the expand function to copy the materialized repository content
/// into the project's external directory.
///
/// Note: This function cannot trigger lazy materialization because it doesn't
/// have access to DICE. The caller should ensure the repo is materialized
/// (via `get_file_ops_delegate`) before calling this function.
pub(crate) async fn copy_to_destination(
    setup: &ExtensionRepoCellSetup,
    project_root: &kuro_fs::paths::abs_norm_path::AbsNormPath,
    dest_path: &std::path::Path,
) -> kuro_error::Result<()> {
    // Compute source path from canonical name
    let source_path = project_root
        .as_path()
        .join("bazel-external")
        .join(setup.canonical_name.as_ref());

    // Check if materialized
    if !source_path.exists() {
        return Err(ExtensionRepoError::NotMaterialized {
            canonical_name: setup.canonical_name.to_string(),
            extension_id: setup.extension_id.to_string(),
        }
        .into());
    }

    // Copy recursively using the same helper as repository_rule
    crate::repository_rule::copy_to_destination_impl(&source_path, dest_path).await
}

/// Create a minimal stub repo for an extension that failed to generate a repo.
///
/// This creates a directory with a BUILD.bazel and WORKSPACE.bazel so that
/// load() calls referencing this repo will find valid (empty) files rather
/// than causing "cell not found" errors.
fn materialize_stub_repo(
    project_root: &std::path::Path,
    canonical_name: &str,
) -> kuro_error::Result<()> {
    let dest = project_root.join("bazel-external").join(canonical_name);
    if !dest.exists() {
        std::fs::create_dir_all(&dest).map_err(|e| {
            kuro_error::kuro_error!(
                kuro_error::ErrorTag::Environment,
                "Failed to create stub repo dir for '{}': {}",
                canonical_name,
                e
            )
        })?;
    }

    // Write a minimal BUILD.bazel
    let build_path = dest.join("BUILD.bazel");
    if !build_path.exists() {
        std::fs::write(
            &build_path,
            "# Stub repo (extension did not generate this repo)\n",
        )
        .map_err(|e| {
            kuro_error::kuro_error!(
                kuro_error::ErrorTag::Environment,
                "Failed to write stub BUILD.bazel for '{}': {}",
                canonical_name,
                e
            )
        })?;
    }

    // Write WORKSPACE.bazel
    let ws_path = dest.join("WORKSPACE.bazel");
    if !ws_path.exists() {
        std::fs::write(&ws_path, "").map_err(|e| {
            kuro_error::kuro_error!(
                kuro_error::ErrorTag::Environment,
                "Failed to write stub WORKSPACE.bazel for '{}': {}",
                canonical_name,
                e
            )
        })?;
    }

    // Write defs.bzl with empty TELEMETRY value (common pattern for telemetry repos)
    let defs_path = dest.join("defs.bzl");
    if !defs_path.exists() {
        std::fs::write(
            &defs_path,
            "# Stub defs.bzl (extension did not generate this repo)\nTELEMETRY = struct(enabled = False)\n",
        )
        .map_err(|e| {
            kuro_error::kuro_error!(
                kuro_error::ErrorTag::Environment,
                "Failed to write stub defs.bzl for '{}': {}",
                canonical_name,
                e
            )
        })?;
    }

    // Mark as complete
    let marker = dest.join(".kuro_repo_complete");
    let _ = std::fs::write(&marker, "stub");

    tracing::info!("Created stub repo for '{}' at {:?}", canonical_name, dest);

    Ok(())
}
