load("@rules_rust//rust:defs.bzl", "rust_library")
load("@slug_crates//:defs.bzl", "crate_edition")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "lock_free_vec",
    srcs = glob(["src/**/*.rs"]),
    edition = crate_edition(),
    deps = ["//allocative/allocative"],
)
