[package]
description = "Slug V2 native configuration descriptor metadata"
edition = "2024"
license = { workspace = true }
name = "slug_configuration_v2"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
blake3 = { workspace = true }
compact_str = { workspace = true }
dupe = { workspace = true }
hex = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true }
slug_identity_v2 = { workspace = true }
strong_hash = { workspace = true }
