load("@rules_rust//rust:defs.bzl", "rust_proc_macro")
load("@slug_crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")

package(default_visibility = ["//visibility:public"])

rust_proc_macro(
    name = "dupe_derive",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    edition = crate_edition(),
    deps = all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)
