load(":defs.bzl", "root_consumer")

root_consumer(name = "valid_tag", dep = "@subject//:valid_tag")
root_consumer(name = "valid_innate", dep = "@subject//:valid_innate")
root_consumer(name = "valid_update_prime", dep = "@subject//:tag_float_update")
root_consumer(name = "tag_alias", dep = "@subject//:tag_alias")
root_consumer(name = "tag_float", dep = "@subject//:tag_float")
root_consumer(name = "tag_print", dep = "@subject//:tag_print")
root_consumer(name = "tag_proxy", dep = "@subject//:tag_proxy")
root_consumer(name = "tag_nested_list", dep = "@subject//:tag_nested_list")
root_consumer(name = "tag_nested_dict", dep = "@subject//:tag_nested_dict")
root_consumer(name = "tag_cycle", dep = "@subject//:tag_cycle")
root_consumer(name = "innate_float", dep = "@subject//:innate_float")
root_consumer(name = "innate_print", dep = "@subject//:innate_print")
root_consumer(name = "innate_nested", dep = "@subject//:innate_nested")
root_consumer(name = "tag_float_update", dep = "@subject//:tag_float_update")
