// Verbatim import bodies; provenance and hashes in fixtures/rustc-map-each/sources.json.
const RUSTC_MAP_EACH_SOURCES: &[(&str, &str)] = &[
    (
        "bazel_skylib/lib/paths.bzl",
        include_str!("../fixtures/rustc-map-each/bazel_skylib/lib/paths.bzl"),
    ),
    (
        "bazel_skylib/rules/common_settings.bzl",
        include_str!("../fixtures/rustc-map-each/bazel_skylib/rules/common_settings.bzl"),
    ),
    (
        "cc_compatibility_proxy/symbols.bzl",
        include_str!("../fixtures/rustc-map-each/cc_compatibility_proxy/symbols.bzl"),
    ),
    (
        "rules_cc/cc/action_names.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/action_names.bzl"),
    ),
    (
        "rules_cc/cc/cc_toolchain_config_lib.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/cc_toolchain_config_lib.bzl"),
    ),
    (
        "rules_cc/cc/common/cc_common.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/common/cc_common.bzl"),
    ),
    (
        "rules_cc/cc/common/cc_helper_internal.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/common/cc_helper_internal.bzl"),
    ),
    (
        "rules_cc/cc/common/cc_info.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/common/cc_info.bzl"),
    ),
    (
        "rules_cc/cc/common/semantics.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/common/semantics.bzl"),
    ),
    (
        "rules_cc/cc/find_cc_toolchain.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/find_cc_toolchain.bzl"),
    ),
    (
        "rules_cc/cc/private/cc_common.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/cc_common.bzl"),
    ),
    (
        "rules_cc/cc/private/cc_info.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/cc_info.bzl"),
    ),
    (
        "rules_cc/cc/private/cc_internal.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/cc_internal.bzl"),
    ),
    (
        "rules_cc/cc/private/cc_launcher_info.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/cc_launcher_info.bzl"),
    ),
    (
        "rules_cc/cc/private/cc_shared_library_hint_info.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/cc_shared_library_hint_info.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/cc_shared_library_info.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/cc_shared_library_info.bzl"),
    ),
    (
        "rules_cc/cc/private/compile/cc_compilation_helper.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/compile/cc_compilation_helper.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/compile/cc_compilation_outputs.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/compile/cc_compilation_outputs.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/compile/compile.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/compile/compile.bzl"),
    ),
    (
        "rules_cc/cc/private/compile/compile_action_templates.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/compile/compile_action_templates.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/compile/compile_build_variables.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/compile/compile_build_variables.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/compile/linkstamp_compile.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/compile/linkstamp_compile.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/compile/lto_compilation_context.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/compile/lto_compilation_context.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/debug_package_info.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/debug_package_info.bzl"),
    ),
    (
        "rules_cc/cc/private/link/cc_linking_helper.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/link/cc_linking_helper.bzl"),
    ),
    (
        "rules_cc/cc/private/link/collect_solib_dirs.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/link/collect_solib_dirs.bzl"),
    ),
    (
        "rules_cc/cc/private/link/cpp_link_action.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/link/cpp_link_action.bzl"),
    ),
    (
        "rules_cc/cc/private/link/create_extra_link_time_library.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/link/create_extra_link_time_library.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/link/create_libraries_to_link_values.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/link/create_libraries_to_link_values.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/link/create_library_to_link.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/link/create_library_to_link.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/link/create_linker_input.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/link/create_linker_input.bzl"),
    ),
    (
        "rules_cc/cc/private/link/create_linking_context_from_compilation_outputs.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/link/create_linking_context_from_compilation_outputs.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/link/create_linkstamp.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/link/create_linkstamp.bzl"),
    ),
    (
        "rules_cc/cc/private/link/finalize_link_action.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/link/finalize_link_action.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/link/link.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/link/link.bzl"),
    ),
    (
        "rules_cc/cc/private/link/link_build_variables.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/link/link_build_variables.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/link/lto_backends.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/link/lto_backends.bzl"),
    ),
    (
        "rules_cc/cc/private/link/lto_indexing_action.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/link/lto_indexing_action.bzl"),
    ),
    (
        "rules_cc/cc/private/link/target_types.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/link/target_types.bzl"),
    ),
    (
        "rules_cc/cc/private/objc_info.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/objc_info.bzl"),
    ),
    (
        "rules_cc/cc/private/paths.bzl",
        include_str!("../fixtures/rustc-map-each/rules_cc/cc/private/paths.bzl"),
    ),
    (
        "rules_cc/cc/private/rules_impl/cc_toolchain_info.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/rules_impl/cc_toolchain_info.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/rules_impl/native_cc_common.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/rules_impl/native_cc_common.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/toolchain_config/cc_toolchain_config_info.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/toolchain_config/cc_toolchain_config_info.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/toolchain_config/configure_features.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/toolchain_config/configure_features.bzl"
        ),
    ),
    (
        "rules_cc/cc/private/toolchain_config/legacy_features.bzl",
        include_str!(
            "../fixtures/rustc-map-each/rules_cc/cc/private/toolchain_config/legacy_features.bzl"
        ),
    ),
    (
        "rules_rust/rust/private/common.bzl",
        include_str!("../fixtures/rustc-map-each/rules_rust/rust/private/common.bzl"),
    ),
    (
        "rules_rust/rust/private/lto.bzl",
        include_str!("../fixtures/rustc-map-each/rules_rust/rust/private/lto.bzl"),
    ),
    (
        "rules_rust/rust/private/pic_utils.bzl",
        include_str!("../fixtures/rustc-map-each/rules_rust/rust/private/pic_utils.bzl"),
    ),
    (
        "rules_rust/rust/private/providers.bzl",
        include_str!("../fixtures/rustc-map-each/rules_rust/rust/private/providers.bzl"),
    ),
    (
        "rules_rust/rust/private/rustc.bzl",
        include_str!("../fixtures/rustc-map-each/rules_rust/rust/private/rustc.bzl"),
    ),
    (
        "rules_rust/rust/private/rustc_resource_set.bzl",
        include_str!("../fixtures/rustc-map-each/rules_rust/rust/private/rustc_resource_set.bzl"),
    ),
    (
        "rules_rust/rust/private/stamp.bzl",
        include_str!("../fixtures/rustc-map-each/rules_rust/rust/private/stamp.bzl"),
    ),
    (
        "rules_rust/rust/private/utils.bzl",
        include_str!("../fixtures/rustc-map-each/rules_rust/rust/private/utils.bzl"),
    ),
];
