/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

use slug_node::attrs::attr_type::source::SourceAttrType;
use slug_node::attrs::coerced_attr::CoercedAttr;
use slug_node::attrs::coercion_context::AttrCoercionContext;
use slug_node::attrs::configurable::AttrIsConfigurable;
use starlark::typing::Ty;
use starlark::values::Value;

use crate::attrs::coerce::AttrTypeCoerce;
use crate::attrs::coerce::attr_type::ty_maybe_select::TyMaybeSelect;
use crate::attrs::coerce::attr_type::unpack_str_or_label;

#[derive(Debug, slug_error::Error)]
#[slug(input)]
enum SourceLabelCoercionError {
    #[error(
        "Couldn't coerce `{0}` as a source.\n  Error when treated as a target: {1:#}\n  Error when treated as a path: {2:#}"
    )]
    CoercionFailed(String, slug_error::Error, slug_error::Error),
}

/// Try cleaning up irrelevant details users often type
fn cleanup_path(value: &str) -> &str {
    let value = value.strip_prefix("./").unwrap_or(value);
    let value = value.strip_suffix("/").unwrap_or(value);
    if value == "." { "" } else { value }
}

impl AttrTypeCoerce for SourceAttrType {
    fn coerce_item(
        &self,
        _configurable: AttrIsConfigurable,
        ctx: &dyn AttrCoercionContext,
        value: Value,
    ) -> slug_error::Result<CoercedAttr> {
        let source_label = unpack_str_or_label(value)?;
        let source_label = source_label.as_str();

        let label_err = if source_label.contains(':') {
            match ctx.coerce_providers_label(source_label) {
                Ok(l) => return Ok(CoercedAttr::SourceLabel(l)),
                Err(e) => Some(e),
            }
        } else {
            // Bazel-compat: bare filenames in `srcs = [...]` that name a
            // predeclared output of another target in the same package (e.g.
            // an `.inc` generated by gentbl_rule) should resolve to the
            // producing target label. Without this, `coerce_path` falls
            // through to a soft "source file missing" and the file is
            // treated as a literal source — DICE then errors out trying
            // to look up an unknown target by that filename.
            if let Some(label) = ctx.output_file_target(cleanup_path(source_label)) {
                return Ok(CoercedAttr::SourceLabel(label));
            }
            // As an optimization, we skip trying to parse as a label in this case
            None
        };

        let path_err = match ctx.coerce_path(cleanup_path(source_label), self.allow_directory) {
            Ok(path) => return Ok(CoercedAttr::SourceFile(path)),
            Err(path_err) => path_err,
        };

        if let Some(label_err) = label_err {
            Err(
                SourceLabelCoercionError::CoercionFailed(value.to_str(), label_err, path_err)
                    .into(),
            )
        } else {
            Err(path_err
                .context(format!("Coercing `{}` as a source", value.to_str()))
                .into())
        }
    }

    fn starlark_type(&self) -> TyMaybeSelect {
        TyMaybeSelect::Basic(Ty::string())
    }
}
